package com.eareyereading.util

/**
 * Collins COBUILD 3星中等常用词汇（字母序）。
 *
 * 数据来源：Collins COBUILD Active Study Dictionary 词频数据。
 * 本表为纯数据，由 [CollinsClassifier] 读取并做小写归一化后用于分级查询；
 * 收录 4226 词（源表 4230 条字面量，其中 4 条为重复——
 * Set 语义下去重不改变任何查询结果）。含少量大写条目，查询侧统一小写后命中。
 */
internal val CollinsStar3Words: Set<String> by lazy { setOf(
    "abandon", "ability", "able", "abortion", "absence", "absolute", "absolutely",
    "absorb", "abstract", "abuse", "academic", "accept", "access", "accident",
    "accompany", "accomplish", "according", "account", "accurate", "achieve", "acid",
    "acquire", "across", "active", "activist", "actor", "actual", "actually",
    "adapt", "add", "address", "adequate", "adjust", "administration", "admire",
    "adolescent", "adult", "advance", "advantage", "adventure", "advertising",
    "advice", "advocate", "affair", "affect", "afford", "afraid", "agency", "agenda",
    "agent", "aggressive", "aging", "agree", "agricultural", "ah", "aircraft",
    "airline", "airport", "alarm", "album", "alcohol", "allegation", "alleged",
    "allocate", "allow", "alliance", "ally", "almost", "alone", "along", "already",
    "also", "alter", "alternative", "although", "always", "amaze", "ambition",
    "ambulance", "amid", "analyze", "ancient", "angel", "anger", "angle", "angry",
    "animal", "announce", "annual", "anonymous", "anticipate", "anxiety", "anybody",
    "apparent", "appeal", "appear", "appetite", "apple", "application", "apply",
    "appoint", "appreciate", "approach", "appropriate", "approval", "approve",
    "approximate", "arbitrary", "architect", "area", "argue", "argument", "arise",
    "army", "arouse", "arrange", "arrest", "arrival", "arrive", "arrow", "article",
    "artifact", "artist", "artistic", "ascend", "aspect", "assault", "assemble",
    "assess", "asset", "assign", "assist", "associate", "association", "assume",
    "assure", "athlete", "atmosphere", "attach", "attack", "attain", "attempt",
    "attend", "attitude", "attorney", "attract", "audience", "author", "authority",
    "auto", "automatic", "available", "avenue", "average", "avoid", "await", "awake",
    "award", "aware", "awful", "awkward", "background", "bacteria", "bag", "balance",
    "ballot", "bang", "banner", "barely", "bargain", "barn", "barrel", "barrier",
    "baseball", "basically", "basis", "bath", "battery", "bay", "beach", "beam",
    "bean", "bear", "beard", "beast", "beauty", "bedroom", "beer", "behalf",
    "behave", "behavior", "being", "belief", "belly", "belong", "below", "bench",
    "bend", "beneath", "benefit", "bent", "beside", "besides", "betray", "beyond",
    "bike", "bill", "binary", "bind", "biology", "bird", "birth", "birthday",
    "biscuit", "bishop", "bite", "bitter", "blade", "blame", "blanket", "blast",
    "blaze", "bleed", "blend", "bless", "blind", "blink", "block", "blood", "bloom",
    "blossom", "blow", "blue", "blunder", "blunt", "blur", "blush", "board", "boast",
    "boat", "body", "bold", "bolt", "bomb", "bond", "bone", "bonus", "book", "boom",
    "boost", "boot", "border", "bore", "boring", "borrow", "boss", "bother",
    "bottle", "bottom", "bounce", "boundary", "bout", "bow", "bowl", "brain",
    "brake", "branch", "brand", "brass", "breach", "bread", "breakfast", "breast",
    "breath", "breathe", "breed", "brick", "bride", "bridge", "brief", "briefly",
    "brigade", "bright", "brilliant", "bring", "brisk", "broad", "broadcast",
    "broader", "broken", "bronze", "broom", "brother", "brow", "brown", "brush",
    "bubble", "bucket", "budget", "buffalo", "bug", "build", "bulk", "bull",
    "bullet", "bump", "bunch", "burden", "bureau", "burial", "burn", "burst", "bury",
    "bush", "business", "busy", "but", "butter", "button", "cabin", "cabinet",
    "cable", "cage", "cake", "calculate", "calendar", "calf", "calm", "calorie",
    "camel", "campaign", "campus", "canal", "cancel", "cancer", "candidate",
    "candle", "canvas", "capable", "capacity", "cape", "capital", "captain",
    "caption", "captive", "capture", "carbon", "cardinal", "cargo", "carol",
    "carpet", "carriage", "carrot", "carry", "cart", "cartoon", "carve", "cash",
    "casino", "cast", "casual", "catalog", "catch", "category", "cattle", "caught",
    "cause", "caution", "cave", "cease", "ceiling", "celebrate", "cell", "cement",
    "cemetery", "census", "center", "ceremony", "chain", "chairman", "chalk",
    "chamber", "champion", "chance", "change", "channel", "chaos", "chapter",
    "character", "charge", "charity", "charm", "chart", "chase", "chat", "cheap",
    "cheat", "check", "cheek", "cheer", "cheerful", "cheese", "chef", "chemical",
    "cherry", "chess", "chest", "chew", "chief", "childhood", "chill", "chimney",
    "chin", "chip", "chocolate", "choice", "cholesterol", "chord", "chore", "chorus",
    "chronic", "chunk", "church", "cigarette", "circle", "circuit", "circular",
    "circumstance", "circus", "cite", "citizen", "civilian", "claim", "clamor",
    "clamp", "clap", "clash", "clasp", "class", "classic", "clause", "claw", "clay",
    "clean", "clearance", "clerk", "clever", "click", "cliff", "climate", "climb",
    "cling", "clinic", "clip", "cloak", "clock", "clone", "close", "closet", "cloth",
    "clothe", "clothing", "cloud", "clown", "club", "clue", "clumsy", "cluster",
    "clutch", "coach", "coal", "coarse", "coast", "coastal", "coating", "coconut",
    "code", "coffee", "coffin", "coil", "coin", "coincide", "coincidence",
    "collapse", "collar", "colleague", "collect", "college", "collision", "colonel",
    "colonial", "colony", "colorful", "column", "comb", "combat", "combination",
    "combine", "comeback", "comedy", "comet", "comfort", "comma", "command",
    "comment", "commerce", "commission", "commit", "commitment", "committee",
    "commodity", "commonplace", "commonwealth", "commune", "communicate",
    "community", "compact", "companion", "company", "compare", "comparison",
    "compassion", "compensate", "compete", "competence", "competition", "compile",
    "complain", "complaint", "complement", "complete", "complex", "complicate",
    "compose", "compound", "compress", "compromise", "compute", "conceive",
    "concentrate", "concentration", "concept", "concern", "concert", "concession",
    "conclude", "conclusion", "concrete", "condemn", "condense", "condition",
    "conduct", "cone", "confer", "conference", "confess", "confidence", "confident",
    "confine", "confirm", "conflict", "confront", "confuse", "congress",
    "connection", "conquer", "consent", "consequence", "conservation",
    "conservative", "considerable", "consist", "consistent", "console", "constant",
    "constitute", "constitutional", "construct", "consult", "consume", "consumer",
    "consumption", "contact", "contain", "contaminate", "contemplate",
    "contemporary", "contempt", "contend", "content", "contest", "context",
    "continent", "continual", "continuation", "contract", "contrast", "contribute",
    "contribution", "contrive", "controversy", "convention", "conventional",
    "conversation", "converse", "conversion", "convert", "convey", "convince",
    "cook", "cookie", "cool", "cooperate", "cope", "copper", "copy", "coral", "cord",
    "core", "cork", "corn", "corner", "corporate", "corporation", "corps",
    "correlate", "correspond", "corridor", "corrupt", "costly", "costume", "council",
    "counsel", "counter", "countryside", "county", "couple", "courage", "courier",
    "course", "courtesy", "courtyard", "cousin", "coverage", "crack", "cracker",
    "craft", "crane", "crash", "crawl", "cream", "create", "creature", "credibility",
    "credit", "creek", "creep", "crew", "cricket", "crime", "criminal", "crisis",
    "crisp", "critic", "critical", "criticism", "criticize", "crop", "cross",
    "crouch", "crowd", "crown", "crucial", "crude", "cruel", "cruise", "crumble",
    "crush", "crust", "crystal", "cube", "cubic", "cucumber", "cultivate",
    "cultural", "culture", "cumulative", "curious", "curl", "currency", "current",
    "curriculum", "curtain", "curve", "cushion", "custom", "customary", "customer",
    "cycle", "dairy", "dam", "damage", "damp", "dance", "dancer", "danger", "dare",
    "darkness", "data", "database", "date", "daughter", "dawn", "daylight",
    "deadline", "deadly", "deaf", "deal", "dean", "debate", "debt", "decade",
    "decay", "deceive", "decent", "decide", "decision", "deck", "declare", "decline",
    "decorate", "decrease", "dedicate", "deed", "deem", "deeply", "deer", "default",
    "defeat", "defect", "defend", "defendant", "defense", "deficit", "define",
    "definite", "degree", "delay", "delegate", "deliberate", "delicate", "delight",
    "deliver", "delivery", "delta", "deluxe", "demand", "democracy", "democrat",
    "democratic", "demonstrate", "denial", "dense", "density", "deny", "depart",
    "department", "departure", "depend", "dependent", "depict", "deploy", "deposit",
    "depression", "deputy", "derive", "descend", "describe", "desert", "deserve",
    "design", "desire", "desk", "despair", "despite", "dessert", "destination",
    "destiny", "destroy", "detail", "detailed", "detect", "determine", "devastate",
    "develop", "device", "devil", "devise", "devote", "diagnose", "diagram", "dial",
    "dialogue", "diameter", "diamond", "diary", "dictate", "differ", "digital",
    "dignity", "dilemma", "dime", "dimension", "diminish", "dine", "dinner",
    "dinosaur", "dioxide", "dip", "diplomatic", "direct", "direction", "director",
    "dirt", "disable", "disagree", "disappear", "disappoint", "disapprove",
    "disaster", "discard", "discharge", "discipline", "disclose", "discount",
    "discourse", "discover", "discrete", "discriminate", "discuss", "disease",
    "disgrace", "disguise", "disgust", "dish", "disk", "dislike", "dismiss",
    "disorder", "dispatch", "dispense", "display", "disposal", "dispose", "dispute",
    "disrupt", "dissolve", "distance", "distant", "distinct", "distinguish",
    "distort", "distract", "district", "disturb", "ditch", "dive", "diverse",
    "divert", "divide", "divine", "division", "divorce", "dizzy", "dock", "doctor",
    "document", "dodge", "dollar", "domain", "dome", "domestic", "dominant",
    "dominate", "donate", "donkey", "donor", "doom", "doorway", "dose", "double",
    "doubt", "dough", "dove", "downhill", "download", "downtown", "dozen", "draft",
    "drag", "dragon", "drain", "drama", "dramatic", "drastic", "draw", "drawer",
    "drawing", "dread", "dream", "dress", "drift", "drill", "drink", "drip", "drive",
    "drop", "drought", "drown", "drum", "drunk", "dual", "duck", "due", "duke",
    "dull", "dumb", "dump", "dune", "dunk", "duplicate", "durable", "duration",
    "during", "dusk", "dust", "dusty", "duty", "dwarf", "dwell", "dynamic",
    "dynasty", "eager", "eagle", "earn", "earnest", "earthquake", "ease", "easily",
    "Easter", "eastern", "echo", "eclipse", "ecology", "economic", "economical",
    "economy", "edge", "edible", "edit", "edition", "editor", "educate", "educator",
    "effect", "effective", "efficiency", "efficient", "effort", "eighteen", "either",
    "elaborate", "elbow", "elderly", "elect", "election", "electric", "electricity",
    "elegant", "element", "elephant", "elevate", "elevator", "eleven", "eligible",
    "eliminate", "elite", "elsewhere", "embark", "embarrass", "embassy", "embrace",
    "emerge", "emergency", "emission", "emotion", "emperor", "emphasis", "empire",
    "employ", "employee", "employer", "empty", "enable", "enact", "encounter",
    "encourage", "endanger", "endorse", "endless", "endure", "enemy", "energy",
    "enforce", "engage", "engine", "engineer", "enhance", "enjoy", "enormous",
    "enough", "enquire", "enrich", "enroll", "ensure", "enterprise", "entertain",
    "enthusiasm", "entire", "entity", "entrance", "entry", "envelope", "environment",
    "envisage", "episode", "equal", "equation", "equip", "equipment", "equivalent",
    "era", "erode", "error", "erupt", "escape", "escort", "especially", "essay",
    "essence", "essential", "establish", "estate", "estimate", "eternal", "ethics",
    "ethnic", "evaluate", "even", "evening", "eventually", "ever", "everybody",
    "evidence", "evident", "evil", "evolution", "evolve", "exact", "exaggerate",
    "exam", "examine", "example", "exceed", "excel", "excellent", "except",
    "exception", "excess", "exchange", "excite", "exclude", "excuse", "execute",
    "executive", "exempt", "exercise", "exhaust", "exhibit", "exile", "exist",
    "exit", "exotic", "expand", "expansion", "expect", "expedition", "expense",
    "expensive", "experiment", "expert", "expire", "explain", "explicit", "explode",
    "exploit", "explore", "export", "expose", "exposure", "express", "extend",
    "extension", "extensive", "extent", "external", "extra", "extract", "extreme",
    "fabric", "fabulous", "face", "facility", "fact", "factor", "factory", "faculty",
    "fade", "fail", "failure", "faint", "fair", "fairly", "fairy", "faith",
    "faithful", "fake", "fall", "false", "fame", "familiar", "family", "famine",
    "famous", "fancy", "fantasy", "fare", "farm", "farmer", "fascinating", "fashion",
    "fast", "fasten", "fatal", "fate", "father", "fatigue", "fault", "favor",
    "favorite", "fear", "feast", "feat", "feather", "feature", "federal", "fee",
    "feed", "feedback", "feel", "fellow", "female", "fence", "fend", "festival",
    "feud", "fever", "fewer", "fiber", "fiction", "field", "fierce", "fifteen",
    "fifth", "fifty", "fight", "fighter", "figure", "file", "fill", "film", "filter",
    "final", "finally", "finance", "financial", "find", "finding", "fine", "finger",
    "finish", "fire", "firm", "first", "fiscal", "fish", "fisherman", "fist",
    "fitness", "fix", "fixture", "flag", "flake", "flame", "flap", "flare", "flash",
    "flask", "flat", "flavor", "flaw", "flee", "fleet", "flesh", "flexibility",
    "flexible", "flick", "flight", "flip", "float", "flock", "flood", "floor",
    "flour", "flourish", "flow", "flower", "flu", "fluid", "flush", "flute", "foam",
    "focus", "fold", "folk", "follow", "fond", "food", "fool", "foolish", "foot",
    "footstep", "forbid", "force", "forecast", "forehead", "foreign", "foremost",
    "foresee", "forest", "forever", "forge", "forget", "forgive", "fork", "form",
    "formal", "format", "former", "formula", "forth", "fortnight", "fortunate",
    "fortune", "forty", "forum", "forward", "fossil", "foster", "foul", "foundation",
    "fountain", "four", "fourth", "fraction", "fragile", "fragment", "frame",
    "framework", "franchise", "frank", "frankly", "fraud", "freak", "free",
    "freedom", "freeze", "freight", "French", "frequency", "frequent", "fresh",
    "friction", "Friday", "fridge", "fried", "friend", "friendly", "friendship",
    "fright", "frog", "from", "front", "frontier", "frost", "frown", "frozen",
    "fruit", "frustrate", "fuel", "fulfill", "full", "fumble", "function", "fund",
    "fundamental", "funeral", "funny", "furious", "furnace", "furnish", "furniture",
    "further", "furthermore", "fuse", "fuss", "futile", "future", "gain", "galaxy",
    "gallery", "gallon", "gamble", "game", "gang", "garage", "garbage", "garden",
    "garlic", "garment", "garrison", "gate", "gateway", "gather", "gauge", "gave",
    "gaze", "gear", "gender", "gene", "general", "generate", "generation",
    "generous", "genetic", "genius", "gentle", "gentleman", "genuine", "gesture",
    "ghost", "giant", "gift", "gifted", "girlfriend", "given", "glad", "gland",
    "glance", "glare", "glass", "gleam", "glimpse", "global", "globe", "gloom",
    "gloomy", "glory", "gloss", "glove", "gloze", "glow", "glue", "goal", "goat",
    "god", "gold", "golden", "golf", "goodness", "goods", "govern", "governor",
    "grace", "grade", "gradual", "graduate", "grain", "grammar", "grand",
    "grandfather", "grandmother", "grandson", "granite", "grape", "graph", "graphic",
    "grasp", "grass", "grateful", "grave", "gravity", "gray", "grease", "greedy",
    "Greek", "green", "greet", "greeting", "grey", "grid", "grief", "grill", "grim",
    "grin", "grind", "grip", "groan", "grocery", "groom", "grope", "gross", "ground",
    "group", "grove", "growl", "grown-up", "growth", "grubby", "guarantee", "guard",
    "guardian", "guess", "guest", "guidance", "guide", "guideline", "guilt",
    "guilty", "guitar", "gulf", "gulp", "gust", "habit", "habitat", "hair",
    "haircut", "half", "halfway", "hall", "halt", "hamburger", "hammer", "hand",
    "handful", "handle", "handsome", "handy", "hang", "happen", "happiness", "happy",
    "harbor", "hard", "hardly", "hardware", "harm", "harmony", "harsh", "harvest",
    "haste", "hasty", "hate", "hatred", "haul", "haunt", "haven", "hawk", "hazard",
    "head", "headline", "headphone", "heal", "health", "heap", "hear", "hearing",
    "heart", "heat", "heater", "heave", "heaven", "heavily", "heavy", "hedge",
    "heel", "height", "heir", "helicopter", "hell", "hello", "helmet", "help",
    "helpful", "hemisphere", "hen", "hence", "herb", "herd", "heritage", "hero",
    "hesitate", "hide", "hierarchy", "highland", "highlight", "highly", "highway",
    "hike", "hill", "hint", "hire", "historian", "historic", "historical", "history",
    "hold", "holder", "hole", "holiday", "hollow", "holy", "home", "homeland",
    "homeless", "homework", "honest", "honestly", "honey", "honor", "hood", "hook",
    "hope", "hopeful", "horizon", "horn", "horror", "horse", "hospital", "host",
    "hostage", "hostile", "hostility", "hotel", "hound", "hour", "household",
    "housewife", "housing", "hover", "however", "howl", "huge", "hull", "human",
    "humble", "humid", "humor", "hundred", "hunger", "hungry", "hunt", "hunter",
    "hurricane", "hurry", "hurt", "husband", "hut", "hydrogen", "hypothesis", "ice",
    "ice-cream", "icon", "idea", "ideal", "identical", "identify", "identity",
    "ideology", "idiom", "idiot", "idle", "idol", "ignorance", "ignorant", "ignore",
    "illegal", "illness", "illuminate", "illustrate", "image", "imagination",
    "imagine", "imitate", "immediate", "immense", "immigrant", "immune", "impact",
    "impair", "impart", "impatient", "implication", "implicit", "imply", "import",
    "importance", "important", "impose", "impossible", "impress", "impression",
    "impressive", "improve", "improvement", "impulse", "incentive", "inch",
    "incident", "incline", "include", "income", "incorporate", "increase",
    "incredible", "indeed", "independence", "independent", "index", "indicate",
    "indication", "indicative", "indirect", "individual", "indoor", "induce",
    "industrial", "industry", "inevitable", "infant", "infect", "infection",
    "inflation", "influence", "inform", "informal", "information", "ingredient",
    "inhabit", "inherit", "initial", "initially", "initiative", "inject", "injure",
    "injury", "ink", "inland", "inn", "inner", "innocent", "innovation", "input",
    "inquire", "inquiry", "insect", "insert", "inside", "insight", "insist",
    "inspect", "inspiration", "install", "instance", "instant", "instead",
    "institute", "institution", "instruct", "instruction", "instrument", "insurance",
    "insure", "integer", "integrate", "integrity", "intellectual", "intelligence",
    "intelligent", "intend", "intense", "intensity", "intensive", "intention",
    "interact", "interaction", "interest", "interesting", "interfere", "internal",
    "international", "internet", "interpret", "interpretation", "interval",
    "intervene", "intervention", "interview", "into", "intrigue", "introduce",
    "introduction", "invade", "invasion", "invent", "invest", "investigate",
    "investigation", "investment", "investor", "invite", "invoke", "involve",
    "involvement", "iron", "irony", "irregular", "isolate", "issue", "item",
    "jacket", "jail", "janitor", "January", "jar", "jaw", "jazz", "jealous",
    "jealousy", "jeans", "jelly", "jeopardize", "jerk", "Jesus", "jewel", "jewelry",
    "job", "join", "joint", "joke", "jolly", "journal", "journalist", "journey",
    "joy", "joyful", "judge", "judgment", "juice", "July", "jump", "June", "jungle",
    "junior", "jury", "just", "justice", "justify", "keen", "keep", "kernel",
    "kettle", "keyboard", "kick", "kid", "kidney", "kill", "killer", "kilogram",
    "kilometer", "kind", "kindness", "kingdom", "kiss", "kit", "kitchen", "kite",
    "knee", "knife", "knight", "knit", "knob", "knock", "knot", "know", "knowledge",
    "label", "laboratory", "labor", "lace", "lack", "ladder", "lady", "lake", "lamb",
    "lame", "lamp", "landlord", "landmark", "landscape", "lane", "language", "lap",
    "laptop", "large", "largely", "laser", "last", "late", "lately", "latest",
    "latter", "laugh", "laughter", "launch", "laundry", "lawn", "lawsuit", "lawyer",
    "layer", "layout", "lazy", "lead", "leader", "leadership", "leading", "leaf",
    "league", "leak", "lean", "leap", "learn", "learning", "lease", "least",
    "leather", "leave", "lecture", "left", "legacy", "legal", "legend",
    "legislation", "legitimate", "leisure", "lemon", "lend", "length", "lens",
    "less", "lesser", "lesson", "letter", "level", "lever", "liability", "liable",
    "liar", "liberal", "liberate", "liberty", "library", "license", "lick", "lid",
    "lie", "lieutenant", "life", "lifetime", "lift", "light", "lightning", "like",
    "likely", "likewise", "limb", "lime", "limit", "limitation", "limited", "limp",
    "line", "linear", "linen", "linger", "link", "lion", "lip", "lipstick", "liquid",
    "liquor", "list", "listen", "listener", "literacy", "literal", "literary",
    "literature", "liter", "litter", "little", "live", "lively", "liver", "living",
    "load", "loan", "lobby", "local", "locate", "location", "lock", "lodge", "loft",
    "logical", "logo", "lone", "lonely", "long", "look", "loop", "loose", "lord",
    "lorry", "lose", "loss", "lost", "loud", "lounge", "love", "lovely", "lover",
    "lower", "loyal", "loyalty", "luck", "lucky", "luggage", "lumber", "lump",
    "lunar", "lunch", "lung", "luxury", "machine", "machinery", "mad", "madam",
    "magazine", "magic", "magnet", "magnetic", "magnificent", "magnitude", "maid",
    "maiden", "mail", "main", "mainland", "mainstream", "maintain", "maintenance",
    "major", "majority", "make", "maker", "makeup", "male", "mall", "mammal", "man",
    "manage", "management", "manager", "mandate", "mandatory", "mankind", "manner",
    "manor", "manual", "manufacture", "manufacturer", "manuscript", "many", "map",
    "maple", "marathon", "marble", "March", "margin", "marginal", "marine", "mark",
    "marker", "market", "marketing", "marriage", "married", "marry", "Mars", "marsh",
    "martial", "mask", "mass", "massacre", "massive", "master", "match", "mate",
    "material", "mathematical", "mathematics", "maths", "matter", "mature",
    "maximum", "maybe", "mayor", "meal", "mean", "meaning", "meaningful", "means",
    "meanwhile", "measure", "measurement", "meat", "mechanic", "mechanical",
    "mechanism", "medal", "media", "median", "medical", "medication", "medicine",
    "medieval", "medium", "meet", "meeting", "mellow", "melody", "melon", "melt",
    "member", "membership", "membrane", "memo", "memoir", "memorable", "memorial",
    "memory", "mental", "mention", "mentor", "menu", "merchant", "mercy", "mere",
    "merely", "merge", "merger", "merit", "merry", "mess", "message", "messy",
    "metal", "metaphor", "meter", "method", "methodology", "middle", "midnight",
    "midst", "might", "mighty", "migrate", "mild", "mile", "military", "milk",
    "mill", "millennium", "million", "mind", "mine", "mineral", "minimal",
    "minimize", "minimum", "mining", "minister", "ministry", "minor", "minority",
    "minus", "minute", "miracle", "mirror", "misery", "miss", "missile", "missing",
    "mission", "mistake", "mistress", "misunderstand", "mixed", "mixture", "moan",
    "mob", "mobile", "mobility", "mock", "mode", "model", "moderate", "modern",
    "modest", "modify", "module", "moist", "moisture", "molecule", "moment",
    "momentum", "Monday", "monetary", "money", "monitor", "monk", "monkey",
    "monopoly", "monster", "month", "monthly", "monument", "mood", "moon", "moral",
    "more", "moreover", "morning", "mortality", "mortgage", "mostly", "mother",
    "motherhood", "motion", "motivate", "motivation", "motive", "motor",
    "motorcycle", "mould", "mount", "mountain", "mouse", "mouth", "movement",
    "movie", "much", "multiple", "multiply", "municipal", "murder", "muscle",
    "museum", "mushroom", "music", "musical", "musician", "must", "mutual",
    "mystery", "myth", "nail", "naive", "naked", "name", "namely", "narrative",
    "narrow", "nasty", "nation", "national", "native", "natural", "nature", "naval",
    "navigate", "navy", "near", "nearby", "nearly", "neat", "necessarily",
    "necessary", "necessity", "neck", "need", "needle", "negative", "neglect",
    "negotiate", "negotiation", "neighbor", "neighborhood", "neither", "nephew",
    "nerve", "nervous", "nest", "network", "neural", "neutral", "never",
    "nevertheless", "newly", "next", "nice", "niche", "nickel", "nickname", "niece",
    "night", "nightmare", "nine", "nineteen", "ninety", "nitrogen", "noble",
    "nobody", "noise", "noisy", "nominal", "nominate", "none", "nonetheless", "norm",
    "normal", "normally", "north", "northern", "nose", "notable", "note", "notebook",
    "nothing", "notice", "notion", "novel", "novelist", "November", "nowhere",
    "nuclear", "nucleus", "number", "numerous", "nurse", "nursery", "nursing",
    "nutrition", "object", "objective", "obligation", "observation", "observe",
    "observer", "obstacle", "obtain", "obvious", "obviously", "occasion",
    "occasional", "occupation", "occupy", "occur", "ocean", "October", "odds",
    "offend", "offense", "offensive", "offer", "office", "officer", "official",
    "offset", "often", "okay", "olive", "Olympic", "once", "ongoing", "onion",
    "online", "only", "onset", "onto", "open", "opening", "openly", "opera",
    "operate", "operating", "operation", "operational", "operative", "operator",
    "opinion", "opponent", "opportunity", "oppose", "opposite", "opposition",
    "optical", "optimism", "optimistic", "option", "orange", "orbit", "orchestra",
    "order", "ordinary", "organ", "organic", "organization", "organize",
    "orientation", "origin", "original", "originally", "other", "otherwise", "ought",
    "ounce", "outcome", "outdoor", "outer", "outfit", "outing", "outlet", "outline",
    "outlook", "output", "outrage", "outrageous", "outset", "outside", "outskirt",
    "outstanding", "oven", "over", "overall", "overcome", "overlook", "overnight",
    "overseas", "overt", "overwhelm", "overwhelming", "owner", "ownership", "oxygen",
    "pace", "pack", "package", "packet", "pact", "pad", "paddle", "page", "pain",
    "painful", "paint", "painter", "painting", "pair", "palace", "pale", "palm",
    "pan", "panel", "panic", "paper", "parade", "paragraph", "parallel", "paralysis",
    "parcel", "pardon", "parent", "parish", "park", "parking", "parliament",
    "parrot", "parsley", "part", "partial", "partially", "participant",
    "participate", "participation", "particle", "particular", "particularly",
    "partly", "partner", "partnership", "party", "pass", "passage", "passenger",
    "passing", "passion", "passive", "passport", "password", "patch", "patent",
    "path", "patience", "patient", "patrol", "patron", "pattern", "pause", "pave",
    "pavement", "payment", "peace", "peaceful", "peach", "peak", "peanut", "pear",
    "pearl", "peasant", "pebble", "peck", "peculiar", "peer", "penalty", "pencil",
    "pending", "penetrate", "penny", "pension", "people", "pepper", "perceive",
    "percent", "percentage", "perception", "perfect", "perfectly", "perform",
    "performance", "perhaps", "period", "permanent", "permission", "permit",
    "persist", "persistent", "person", "personal", "personality", "personally",
    "personnel", "perspective", "persuade", "pessimistic", "pet", "petition",
    "petrol", "phase", "phenomenon", "philosopher", "philosophical", "philosophy",
    "phone", "photo", "photograph", "photographer", "photography", "phrase",
    "physical", "physically", "physician", "physics", "pianist", "piano", "pick",
    "pickup", "picture", "piece", "pier", "pile", "pill", "pillar", "pillow",
    "pilot", "pin", "pinch", "pine", "pink", "pint", "pioneer", "pipe", "pirate",
    "pistol", "pit", "pitch", "pity", "pizza", "place", "plain", "plaintiff",
    "planet", "planner", "plant", "plantation", "plasma", "plastic", "plate",
    "platform", "platter", "playground", "plaza", "plea", "plead", "pleasant",
    "please", "pleased", "pleasure", "pledge", "plenty", "plum", "plunge", "plural",
    "plus", "plush", "pocket", "poem", "poet", "poetry", "point", "poison", "polar",
    "pole", "police", "policeman", "policy", "polish", "polite", "political",
    "politically", "politician", "politics", "poll", "pollute", "pollution", "pond",
    "pony", "pool", "poor", "poorly", "pope", "population", "porcelain", "porch",
    "pork", "port", "portable", "portal", "portion", "portrait", "portray", "pose",
    "position", "positive", "possess", "possession", "possibility", "possible",
    "possibly", "post", "postcard", "poster", "postpone", "pot", "potato",
    "potential", "potentially", "pottery", "poultry", "pound", "pour", "poverty",
    "powder", "power", "powerful", "practical", "practically", "practice",
    "practitioner", "praise", "pray", "prayer", "preach", "precious", "precise",
    "precisely", "precision", "predict", "prediction", "predominant", "prefer",
    "preferable", "preference", "pregnant", "prejudice", "preliminary", "premier",
    "premise", "premium", "preparation", "prepare", "prescribe", "prescription",
    "presence", "present", "presentation", "presently", "preservation", "preserve",
    "presidency", "president", "presidential", "press", "pressure", "presumably",
    "presume", "pretend", "pretty", "prevail", "prevent", "previous", "previously",
    "price", "pride", "priest", "primarily", "primary", "prime", "primitive",
    "prince", "princess", "principal", "principle", "print", "printer", "printing",
    "prior", "priority", "prison", "prisoner", "privacy", "private", "privilege",
    "prize", "probable", "probably", "probe", "problem", "procedure", "proceed",
    "process", "processing", "processor", "produce", "producer", "product",
    "production", "productive", "productivity", "profession", "professional",
    "professor", "profile", "profit", "profound", "program", "programme", "progress",
    "progressive", "prohibit", "project", "prolong", "prominent", "promise",
    "promote", "promotion", "prompt", "proof", "proper", "properly", "property",
    "proportion", "proposal", "propose", "proposed", "prosecutor", "prospect",
    "prosperity", "protect", "protection", "protein", "protest", "protocol", "proud",
    "prove", "provide", "provider", "province", "provincial", "provision", "provoke",
    "psychological", "psychology", "public", "publication", "publicity", "publicly",
    "publish", "publisher", "pull", "pulse", "pump", "punch", "punctual", "punish",
    "punishment", "pupil", "puppet", "puppy", "purchase", "pure", "purple",
    "purpose", "pursue", "pursuit", "puzzle", "qualification", "qualify", "quality",
    "quantity", "quarrel", "quarter", "quarterly", "queen", "query", "quest",
    "question", "quick", "quickly", "quiet", "quietly", "quit", "quite", "quota",
    "quotation", "quote", "rabbit", "racial", "racism", "rack", "radar", "radiation",
    "radical", "radio", "rage", "raid", "rail", "railroad", "railway", "rain",
    "rainbow", "rainy", "raise", "rally", "ranch", "random", "range", "ranger",
    "rank", "rapid", "rapidly", "rare", "rarely", "rate", "rather", "ratio",
    "rational", "raw", "reach", "react", "reaction", "read", "reader", "readily",
    "reading", "ready", "real", "realistic", "reality", "realize", "really", "realm",
    "reap", "rear", "reason", "reasonable", "reasonably", "rebel", "rebellion",
    "rebuke", "recall", "receipt", "receive", "receiver", "recent", "recently",
    "reception", "recipe", "recipient", "recital", "reckon", "recognition",
    "recognize", "recommend", "recommendation", "reconcile", "record", "recording",
    "recover", "recovery", "recreation", "recruit", "recruitment", "recycle", "red",
    "reduce", "reduction", "refer", "referee", "reference", "referendum", "reflect",
    "reflection", "reform", "refugee", "refuse", "regard", "regarding", "regardless",
    "regime", "region", "regional", "register", "registration", "regret", "regular",
    "regularly", "regulate", "regulation", "regulatory", "reinforce", "reject",
    "relate", "related", "relation", "relationship", "relative", "relatively",
    "relax", "release", "relevant", "reliability", "reliable", "reliance", "relief",
    "relieve", "religion", "religious", "reluctant", "rely", "remain", "remainder",
    "remaining", "remains", "remark", "remarkable", "remedy", "remember", "remind",
    "remote", "removal", "remove", "renaissance", "render", "renew", "rent",
    "rental", "repair", "repay", "repeat", "repeatedly", "replace", "replacement",
    "reply", "report", "reporter", "represent", "representation", "representative",
    "republic", "republican", "reputation", "request", "require", "requirement",
    "rescue", "research", "researcher", "resemble", "reservation", "reserve",
    "resident", "residential", "resign", "resignation", "resist", "resistance",
    "resolution", "resolve", "resort", "resource", "respect", "respectable",
    "respectful", "respond", "respondent", "response", "responsibility",
    "responsible", "rest", "restaurant", "restless", "restore", "restrict",
    "restriction", "restrictive", "result", "resultant", "retain", "retire",
    "retirement", "retreat", "return", "reveal", "revenue", "reverse", "review",
    "revise", "revision", "revival", "revolution", "revolutionary", "reward",
    "rhetoric", "rhythm", "rice", "rich", "rid", "ride", "rider", "ridge", "rifle",
    "rift", "right", "rigid", "rigorous", "ring", "riot", "rip", "ripe", "rise",
    "risk", "risky", "ritual", "rival", "river", "road", "roam", "roar", "roast",
    "rob", "robbery", "robot", "robust", "rock", "rocket", "rocky", "rod", "role",
    "roll", "roller", "Roman", "romance", "romantic", "roof", "room", "root", "rope",
    "rose", "rotate", "rotation", "rough", "roughly", "round", "route", "routine",
    "row", "royal", "rub", "rubber", "rubbish", "rude", "ruin", "rule", "ruler",
    "rumor", "rural", "rush", "Russian", "sack", "sacred", "sacrifice", "sad",
    "sadness", "sadly", "safe", "safeguard", "safely", "safety", "sail", "sailor",
    "saint", "salad", "salary", "sale", "salesman", "salmon", "salon", "salt",
    "salvation", "same", "sample", "sanction", "sanctuary", "sand", "sandal",
    "sandwich", "satellite", "satire", "satisfaction", "satisfy", "saturate",
    "Saturday", "sauce", "savage", "save", "saving", "saw", "say", "scale", "scan",
    "scandal", "scared", "scarce", "scarcely", "scare", "scarf", "scary", "scatter",
    "scenario", "scene", "scenery", "schedule", "scheme", "scholar", "scholarship",
    "school", "science", "scientific", "scientist", "scope", "score", "scorn",
    "scout", "scramble", "scrap", "scrape", "scratch", "scream", "screen",
    "screenplay", "screw", "script", "sculpture", "seal", "search", "season", "seat",
    "second", "secondary", "secret", "secretary", "section", "sector", "secular",
    "secure", "security", "seed", "seek", "seem", "seemingly", "segment", "seize",
    "seldom", "select", "selection", "seller", "semester", "seminar", "senate",
    "senator", "send", "senior", "sensation", "sense", "sensibility", "sensible",
    "sensitive", "sensitivity", "sentence", "sentiment", "separate", "separately",
    "separation", "September", "sequence", "series", "serious", "seriously",
    "servant", "serve", "server", "service", "session", "setting", "settle",
    "settlement", "setup", "seven", "seventeen", "seventh", "seventy", "sever",
    "severe", "shade", "shadow", "shaft", "shake", "shall", "shallow", "shame",
    "shape", "share", "shareholder", "shark", "sharp", "shatter", "shed", "sheer",
    "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship", "shipment",
    "shirt", "shock", "shoe", "shoot", "shooting", "shop", "shopping", "shore",
    "short", "shortage", "shortly", "shot", "should", "shoulder", "shout", "show",
    "shower", "showcase", "shrimp", "shrink", "shrub", "shrug", "shut", "shuttle",
    "sibling", "sick", "side", "siege", "sigh", "sight", "sign", "signal",
    "signature", "significance", "significant", "significantly", "silence", "silent",
    "silk", "silly", "silver", "similar", "similarly", "simple", "simplicity",
    "simplify", "simply", "simulate", "simultaneous", "since", "sincere", "sing",
    "singer", "single", "sink", "sir", "sister", "site", "situation", "six",
    "sixteen", "sixth", "sixty", "size", "skeleton", "skeptical", "sketch", "ski",
    "skill", "skilled", "skin", "skip", "skirt", "skull", "slave", "slavery",
    "sleep", "sleepy", "sleeve", "slender", "slice", "slide", "slight", "slightly",
    "slim", "slip", "slit", "slope", "slot", "slow", "slowly", "small", "smart",
    "smartphone", "smash", "smell", "smile", "smoke", "smoker", "smooth", "smoothly",
    "snake", "snap", "snatch", "sneak", "snow", "snowy", "so", "soak", "soap",
    "soar", "soccer", "social", "socialism", "socialist", "society", "sock",
    "socket", "soda", "sofa", "soft", "software", "soil", "solar", "soldier", "sole",
    "solely", "solemn", "solid", "solidarity", "solution", "solve", "some",
    "somebody", "somehow", "someone", "something", "sometimes", "somewhat",
    "somewhere", "son", "song", "soon", "sophisticated", "sore", "sorrow", "sorry",
    "sort", "sought", "soul", "sound", "soup", "sour", "source", "south",
    "southeast", "southern", "southwest", "souvenir", "sovereignty", "Soviet",
    "space", "spacecraft", "spacious", "spade", "span", "Spanish", "spare", "spark",
    "speak", "speaker", "speaking", "spear", "special", "specialist", "specially",
    "species", "specific", "specifically", "specification", "specify", "specimen",
    "spectacle", "spectacular", "spectator", "spectrum", "speculation", "speech",
    "speed", "spell", "spelling", "spend", "spending", "sphere", "spice", "spider",
    "spill", "spin", "spine", "spiral", "spirit", "spiritual", "spite", "split",
    "spoil", "spoke", "spoken", "sponsor", "spontaneous", "spoon", "sport", "spot",
    "spouse", "spray", "spread", "spring", "sprint", "spy", "squad", "square",
    "squeeze", "stability", "stable", "stack", "stadium", "staff", "stage", "stain",
    "stair", "stake", "stale", "stall", "stamp", "stance", "stand", "standard",
    "standing", "star", "stare", "stark", "start", "startup", "state", "statement",
    "station", "statistical", "statistics", "statue", "status", "statute", "stay",
    "steady", "steak", "steal", "steam", "steel", "steep", "steer", "stem", "step",
    "stereotype", "stick", "stiff", "stiffness", "still", "sting", "stir", "stock",
    "stocking", "stomach", "stone", "stool", "stop", "storage", "store", "storm",
    "story", "straight", "straightforward", "strain", "strange", "stranger",
    "strategic", "strategy", "straw", "strawberry", "stray", "streak", "stream",
    "street", "strength", "strengthen", "stress", "stretch", "strict", "strictly",
    "stride", "strike", "string", "strip", "stripe", "strive", "stroke", "strong",
    "strongly", "structural", "structure", "struggle", "stubborn", "student",
    "studio", "study", "stuff", "stumble", "stunning", "stupid", "sturdy", "style",
    "subject", "submit", "subsequent", "subsequently", "substance", "substantial",
    "substantially", "substitute", "subtle", "suburb", "succeed", "success",
    "successful", "successfully", "such", "suck", "sudden", "suddenly", "suffer",
    "sufficient", "sugar", "suggest", "suggestion", "suicide", "suit", "suite",
    "suitable", "sultan", "sum", "summary", "summer", "summit", "summon", "Sunday",
    "sunlight", "sunny", "sunrise", "sunset", "super", "superb", "superficial",
    "superior", "supervise", "supervision", "supervisor", "supper", "supplement",
    "supply", "support", "supporter", "suppose", "supposed", "supposedly",
    "suppress", "supreme", "sure", "surely", "surface", "surgeon", "surgery",
    "surplus", "surprise", "surprised", "surprising", "surprisingly", "surrender",
    "surround", "surrounding", "survey", "survival", "survive", "survivor",
    "suspect", "suspend", "suspicion", "suspicious", "sustain", "swallow", "swamp",
    "swan", "swap", "swear", "sweat", "sweater", "sweep", "sweet", "swell", "swift",
    "swim", "swing", "switch", "sword", "symbol", "symbolic", "sympathy", "symptom",
    "syndrome", "syntax", "system", "systematic", "table", "tablet", "tackle",
    "tactic", "tail", "tailor", "take", "tale", "talent", "talented", "talk", "tall",
    "tame", "tank", "tap", "tape", "target", "tariff", "task", "taste", "tax",
    "taxi", "tea", "teach", "teacher", "teaching", "team", "tear", "technical",
    "technically", "technique", "technology", "teenager", "telecommunication",
    "telephone", "telescope", "television", "tell", "temper", "temperature",
    "temple", "temporary", "tempt", "tenant", "tend", "tendency", "tender", "tennis",
    "tense", "tension", "tent", "term", "terminal", "terms", "terrace", "terrain",
    "terrible", "terrific", "territory", "terror", "terrorism", "terrorist", "test",
    "testify", "testimony", "text", "textbook", "textile", "texture", "than",
    "thank", "that", "theater", "theft", "their", "them", "theme", "themselves",
    "then", "theoretical", "theory", "therapy", "there", "thereafter", "thereby",
    "therefore", "thermal", "these", "thesis", "they", "thick", "thickness", "thief",
    "thin", "thing", "think", "thinking", "third", "thirst", "thirsty", "thirteen",
    "thirty", "this", "thorough", "thoroughly", "those", "though", "thought",
    "thousand", "thread", "threat", "threaten", "three", "threshold", "thrill",
    "thrive", "throat", "throne", "through", "throughout", "throw", "thrust",
    "thumb", "thunder", "Thursday", "thus", "tick", "ticket", "tide", "tidy", "tie",
    "tiger", "tight", "tightly", "tile", "till", "timber", "time", "timid", "tiny",
    "tip", "tissue", "title", "to", "toast", "tobacco", "today", "toe", "together",
    "toilet", "token", "tolerance", "tolerant", "toll", "tomato", "tomb", "tomorrow",
    "tone", "tongue", "tonight", "too", "took", "tool", "tooth", "top", "topic",
    "torch", "torture", "toss", "total", "totally", "touch", "tough", "tour",
    "tourism", "tourist", "tournament", "toward", "towards", "towel", "tower",
    "town", "toxic", "toy", "trace", "track", "trade", "trader", "trading",
    "tradition", "traditional", "traffic", "tragedy", "trail", "trailer", "train",
    "trainer", "training", "trait", "transaction", "transcript", "transfer",
    "transform", "transformation", "transition", "translate", "translation",
    "transmission", "transmit", "transparency", "transparent", "transplant",
    "transport", "transportation", "trap", "trash", "travel", "traveler", "tray",
    "treasure", "treat", "treatment", "treaty", "tree", "tremendous", "trend",
    "trial", "triangle", "tribe", "tribute", "trick", "trigger", "trim", "trip",
    "triumph", "trolley", "troop", "trophy", "tropical", "trouble", "truck", "true",
    "truly", "trunk", "trust", "truth", "try", "tube", "Tuesday", "tuition",
    "tumble", "tumor", "tune", "tunnel", "turkey", "turn", "turning", "tutor",
    "tutorial", "twelve", "twenty", "twice", "twin", "twist", "type", "typical",
    "typically", "ugly", "ultimate", "ultimately", "umbrella", "unable", "uncle",
    "under", "undergo", "undergraduate", "underground", "underlying", "undermine",
    "underneath", "understand", "understanding", "undertake", "unemployment",
    "unexpected", "unfair", "unfold", "unfortunate", "unfortunately", "unhappy",
    "uniform", "union", "unique", "unit", "unite", "united", "unity", "universal",
    "universe", "university", "unknown", "unless", "unlike", "unlikely", "until",
    "unusual", "up", "update", "upgrade", "upon", "upper", "upset", "urban", "urge",
    "urgent", "us", "usage", "use", "used", "useful", "user", "usual", "usually",
    "utility", "utilize", "vacant", "vacation", "vaccine", "vacuum", "vague", "vain",
    "valid", "valley", "valuable", "value", "valve", "van", "vanish", "variable",
    "variation", "varied", "variety", "various", "vary", "vast", "vegetable",
    "vehicle", "vein", "velvet", "vendor", "venture", "venue", "verb", "verdict",
    "verify", "verse", "version", "versus", "vertical", "very", "vessel", "veteran",
    "via", "viable", "victim", "victory", "video", "view", "viewer", "viewpoint",
    "village", "villager", "violate", "violation", "violence", "violent", "violet",
    "virgin", "virtual", "virtually", "virtue", "virus", "visible", "vision",
    "visit", "visitor", "visual", "vital", "vivid", "vocabulary", "vocal", "voice",
    "void", "volatile", "volleyball", "volume", "voluntary", "volunteer", "vote",
    "voter", "voting", "voyage", "vulnerable", "wage", "wagon", "waist", "wait",
    "waiter", "wake", "walk", "wall", "wander", "want", "war", "ward", "warehouse",
    "warm", "warmth", "warn", "warning", "warrant", "warranty", "warrior", "wash",
    "waste", "watch", "water", "wave", "way", "we", "weak", "weakness", "wealth",
    "wealthy", "weapon", "wear", "weather", "weave", "wedding", "Wednesday", "weed",
    "week", "weekend", "weekly", "weep", "weigh", "weight", "weird", "welcome",
    "welfare", "well", "west", "western", "wet", "whale", "what", "whatever",
    "wheat", "wheel", "when", "whenever", "where", "whereas", "wherever", "whether",
    "which", "while", "whisper", "whistle", "white", "whoever", "whole", "whom",
    "whose", "wicked", "wide", "widely", "widen", "widespread", "widow", "width",
    "wife", "wild", "wilderness", "wildlife", "will", "willing", "wind", "window",
    "wine", "wing", "winner", "winter", "wipe", "wire", "wisdom", "wise", "wish",
    "witch", "with", "withdraw", "withdrawal", "within", "without", "witness",
    "woke", "woken", "wolf", "woman", "wonder", "wonderful", "wood", "wooden",
    "wool", "word", "work", "worker", "working", "workout", "workshop", "world",
    "worldwide", "worm", "worn", "worried", "worry", "worse", "worship", "worst",
    "worth", "worthwhile", "worthy", "would", "wound", "wrap", "wrath", "wreck",
    "wrestle", "wrist", "write", "writer", "writing", "wrong", "yard", "yeah",
    "year", "yell", "yellow", "yes", "yesterday", "yet", "yield", "you", "young",
    "youngster", "your", "yours", "yourself", "youth", "zero"
) }
