package com.eareyereading.util

/**
 * Collins COBUILD 4星较不常用词汇（字母序）。
 *
 * 数据来源：Collins COBUILD Active Study Dictionary 词频数据。
 * 本表为纯数据，由 [CollinsClassifier] 读取并做小写归一化后用于分级查询；
 * 收录 1913 词（源表 1919 条字面量，其中 6 条为重复——
 * Set 语义下去重不改变任何查询结果）。含少量大写条目，查询侧统一小写后命中。
 */
internal val CollinsStar4Words: Set<String> by lazy { setOf(
    "abandon", "abandonment", "abortion", "absence", "absolute", "absolutely",
    "absorb", "abstract", "abuse", "academic", "accelerate", "accept", "access",
    "accident", "accommodate", "accompany", "accomplish", "account", "accurate",
    "achieve", "acid", "acquire", "adapt", "adequate", "adjust", "administration",
    "admire", "adolescent", "adult", "advance", "advantage", "adventure", "advocate",
    "affair", "aggregate", "aggressive", "agriculture", "alarm", "album", "alcohol",
    "allegation", "allocate", "alter", "alternative", "amaze", "ambition",
    "ambulance", "analyze", "ancient", "anger", "angle", "annual", "anonymous",
    "anticipate", "anxiety", "apparent", "appeal", "appetite", "appreciate",
    "approach", "appropriate", "approval", "arbitrary", "architect", "area",
    "argument", "arise", "army", "arouse", "arrange", "arrest", "artificial",
    "ascend", "aspect", "assault", "assemble", "assess", "asset", "assign", "assist",
    "associate", "association", "assure", "athlete", "atmosphere", "attach",
    "attain", "attempt", "attend", "attitude", "attorney", "attract", "authority",
    "automatic", "available", "avenue", "average", "await", "award", "aware",
    "awful", "awkward", "bacteria", "balance", "barrier", "battery", "behavior",
    "beneath", "benefit", "betray", "bias", "billion", "biological", "birth",
    "bitter", "blame", "blanket", "bleed", "blend", "bless", "block", "bloom",
    "blunder", "bonus", "boom", "boost", "boundary", "breach", "breast", "breath",
    "bribe", "brief", "brilliant", "broad", "broadcast", "broker", "bronze",
    "browse", "brutal", "bubble", "budget", "buffer", "burden", "bureau", "bypass",
    "cabinet", "calculate", "calendar", "calorie", "campaign", "campus", "cancel",
    "candidate", "canvas", "capacity", "capture", "carbon", "career", "carrier",
    "cash", "cast", "casualty", "cattle", "cement", "census", "ceremony",
    "certificate", "chaos", "chapter", "character", "charge", "charity", "charm",
    "chart", "charter", "chase", "cheat", "cheer", "chemical", "cherish", "chief",
    "childhood", "chill", "chronic", "chunk", "circuit", "circular", "civilian",
    "claim", "clash", "classical", "clause", "client", "climate", "clue", "cluster",
    "coast", "coincide", "collapse", "colleague", "column", "combat", "combine",
    "comfort", "command", "comment", "commission", "commit", "commodity",
    "commonwealth", "communicate", "community", "companion", "compel", "competent",
    "compile", "complaint", "complement", "complex", "comply", "compose", "compound",
    "comprehensive", "compress", "compute", "concede", "conceive", "concentrate",
    "concept", "concern", "conclude", "concrete", "condemn", "conduct", "confer",
    "confess", "confine", "confirm", "conflict", "confront", "confuse", "congress",
    "conjunction", "conquest", "conscience", "consensus", "consent", "consequence",
    "conservation", "conservative", "considerable", "consistent", "console",
    "consolidate", "conspiracy", "constant", "construct", "consult", "consume",
    "contempt", "contest", "context", "contingent", "contract", "contradict",
    "contrary", "contrast", "controversy", "convention", "convert", "convince",
    "cooperate", "coordinate", "cope", "corporate", "correspond", "corruption",
    "council", "counsel", "counter", "couple", "coupon", "courage", "coverage",
    "crack", "craft", "crash", "creative", "creature", "credentials", "credibility",
    "credit", "crisis", "criterion", "critic", "crucial", "crude", "cruel", "crush",
    "crystal", "cube", "cultivate", "culture", "curiosity", "currency", "current",
    "curriculum", "curse", "curve", "cushion", "cycle", "database", "debate", "debt",
    "decade", "deceive", "decent", "decisive", "declare", "decline", "decorate",
    "decrease", "dedicate", "deduct", "deem", "default", "defect", "defend",
    "deficit", "define", "delegate", "deliberate", "delicate", "delight", "deliver",
    "demand", "democracy", "democratic", "demolish", "denial", "denounce", "dense",
    "deny", "depart", "department", "dependent", "depict", "deploy", "deposit",
    "depress", "depression", "deputy", "derive", "descend", "deserve", "designate",
    "desire", "despatch", "desperate", "despite", "destiny", "destroy", "detach",
    "detail", "detect", "deter", "determine", "devastate", "develop", "devise",
    "devote", "diagnose", "dialect", "dialogue", "diameter", "dictate", "differ",
    "differentiate", "dimension", "diminish", "diplomat", "disappoint", "disaster",
    "discipline", "disclose", "discount", "discourse", "discover", "discrete",
    "discriminate", "disgrace", "disguise", "disgust", "dismiss", "disorder",
    "dispatch", "dispense", "displace", "display", "disposal", "dispose", "dispute",
    "disrupt", "dissolve", "distinguish", "distort", "distract", "distribute",
    "district", "disturb", "diverse", "divert", "divide", "divorce", "dock",
    "document", "domain", "domestic", "dominant", "dominate", "donate", "doom",
    "doubt", "download", "downtown", "draft", "drag", "drain", "drama", "drastic",
    "drawback", "dread", "drift", "drill", "drip", "drought", "dumb", "dump",
    "duplicate", "durable", "duration", "dusk", "dwarf", "dwell", "dynamic",
    "dynasty", "eager", "eclipse", "ecology", "economical", "economy", "edge",
    "edible", "edit", "editor", "educate", "educator", "effect", "efficiency",
    "efficient", "elaborate", "elbow", "elderly", "elect", "election", "electric",
    "electricity", "elegant", "element", "elevate", "eligible", "elite", "embark",
    "embarrass", "embassy", "embrace", "emerge", "emergency", "emission", "emotion",
    "emperor", "emphasis", "empire", "employ", "employee", "employer", "enact",
    "encounter", "endanger", "endorse", "endless", "endure", "enforce", "engage",
    "engineer", "enhance", "enormous", "enrich", "enroll", "ensure", "enterprise",
    "entertain", "enthusiasm", "entity", "entry", "envelope", "environment",
    "envisage", "episode", "equal", "equation", "equip", "equity", "equivalent",
    "erode", "error", "erupt", "escalate", "escape", "essence", "essential",
    "estimate", "eternal", "ethics", "ethnic", "evaluate", "eventually", "evidence",
    "evident", "evil", "evolution", "evolve", "exaggerate", "exceed", "excel",
    "exception", "excess", "exchange", "excite", "exclude", "excuse", "execute",
    "exempt", "exercise", "exhaust", "exhibit", "exile", "existence", "exit",
    "exotic", "expand", "expansion", "expect", "expedition", "expense",
    "experimental", "expertise", "expire", "explicit", "explode", "exploit",
    "explore", "export", "expose", "exposure", "extend", "extension", "extensive",
    "extent", "external", "extract", "extreme", "fabric", "fabulous", "facility",
    "factor", "faculty", "fade", "failure", "faint", "fairly", "faith", "fake",
    "fame", "familiar", "famine", "fancy", "fantasy", "fascinating", "fashion",
    "fasten", "fatal", "fate", "fatigue", "fault", "favor", "feasible", "feature",
    "federal", "fee", "feedback", "fellow", "female", "fence", "festival", "fever",
    "fiber", "fiction", "fierce", "figure", "filter", "final", "finance", "finite",
    "fiscal", "fitness", "fixture", "flame", "flap", "flare", "flash", "flavor",
    "flaw", "fleet", "flesh", "flexibility", "fling", "flock", "flood", "flour",
    "flu", "fluid", "flush", "flutter", "foam", "focus", "fold", "folk", "forbid",
    "forecast", "forehead", "foremost", "foresee", "forge", "forgive", "formal",
    "format", "formula", "forth", "fortune", "forum", "fossil", "foster", "foul",
    "fraction", "fragile", "fragment", "framework", "franchise", "frank", "frankly",
    "fraud", "freak", "freeze", "freight", "frequency", "frequent", "friction",
    "fright", "fringe", "frontier", "frost", "frustrate", "fulfill", "function",
    "fundamental", "funeral", "furious", "furnace", "furnish", "furniture", "fuse",
    "fuss", "futile", "galaxy", "gallery", "gallon", "gamble", "gang", "garage",
    "garbage", "garrison", "gauge", "gaze", "gear", "gene", "generate", "generation",
    "generous", "genetic", "genius", "genuine", "gesture", "ghost", "gigantic",
    "given", "glance", "glare", "gleam", "glimpse", "global", "globe", "gloom",
    "gloomy", "glory", "gloss", "glove", "glue", "gorgeous", "gown", "grab", "grace",
    "gradual", "graduate", "grain", "grammar", "grand", "grasp", "grateful", "grave",
    "gravity", "grease", "greed", "grief", "grill", "grim", "grin", "grind", "grip",
    "groan", "groom", "gross", "grove", "growth", "guarantee", "guideline", "guilt",
    "guitar", "gulf", "gulp", "gust", "habitat", "hail", "handful", "handle",
    "handy", "harbor", "hardly", "hardware", "harmony", "harsh", "harvest", "haste",
    "hatred", "haul", "haunt", "hazard", "headline", "heal", "heap", "hearing",
    "heaven", "hectic", "heel", "heir", "hemisphere", "hence", "herb", "heritage",
    "hesitate", "hierarchy", "highlight", "hike", "hint", "historian", "historic",
    "hoist", "holder", "hollow", "homeless", "honey", "hood", "hook", "hopeful",
    "horizon", "horror", "hospitality", "hound", "household", "housing", "hover",
    "however", "huddle", "hug", "hull", "humble", "humid", "humor", "hypothesis",
    "hysteria", "ideology", "idiom", "ignorance", "ignorant", "ignore", "illegal",
    "illness", "illuminate", "illusion", "illustrate", "immense", "immigrant",
    "immune", "impact", "impair", "impart", "impatient", "implication", "implicit",
    "imply", "import", "importance", "impose", "impossible", "impress", "impression",
    "impressive", "improvement", "impulse", "incentive", "incident", "incline",
    "incorporate", "incredible", "independence", "index", "indication", "indicative",
    "indirect", "individual", "indoor", "induce", "industrial", "inevitable",
    "infant", "infect", "inflation", "influence", "inform", "informal", "inhabit",
    "inherit", "initial", "initially", "initiative", "inject", "inland",
    "innovation", "input", "inquiry", "insert", "insight", "inspect", "inspiration",
    "install", "instance", "instant", "institute", "instruct", "instrument",
    "insult", "insurance", "intact", "integrate", "integrity", "intellectual",
    "intelligence", "intend", "intense", "intensity", "intensive", "intention",
    "interact", "interaction", "interfere", "internal", "interpret", "interval",
    "intervene", "intervention", "intrigue", "introduce", "introduction", "invade",
    "invasion", "invalid", "invent", "invest", "investigate", "investigation",
    "investor", "invitation", "invoke", "involvement", "iron", "irony", "irregular",
    "isolate", "item", "jail", "jealous", "jealousy", "jeopardize", "jerk", "jewel",
    "joint", "jolly", "journal", "journalist", "journey", "judge", "judgment",
    "junction", "jungle", "jurisdiction", "jury", "justice", "justify", "keen",
    "kernel", "kettle", "kidney", "kin", "kindness", "kingdom", "kit", "knight",
    "knit", "knob", "knot", "label", "laboratory", "lace", "ladder", "lag", "lamb",
    "lame", "lamp", "landlord", "landmark", "landscape", "lane", "lap", "laptop",
    "laser", "latter", "launch", "laundry", "lawn", "lawsuit", "layer", "layout",
    "lazy", "leaf", "league", "leak", "leap", "lease", "legacy", "legend",
    "legislation", "legitimate", "lend", "lens", "lesser", "liberal", "liberate",
    "liberty", "license", "lick", "lifetime", "lightning", "likewise", "limb",
    "lime", "limitation", "limp", "linear", "linen", "linger", "lip", "liquid",
    "liquor", "listener", "literacy", "literal", "literary", "litter", "lively",
    "liver", "living", "lobby", "local", "locate", "location", "lodge", "loft",
    "logical", "logo", "lonely", "loop", "loose", "lottery", "lounge", "lover",
    "lower", "loyal", "loyalty", "luggage", "lumber", "lunar", "luxury", "machinery",
    "madam", "magic", "magnet", "magnificent", "magnitude", "maid", "mainstream",
    "maintenance", "major", "manipulate", "manner", "manor", "manual", "manufacture",
    "manuscript", "maple", "marathon", "marble", "margin", "marginal", "marine",
    "marker", "marketing", "marriage", "marsh", "martial", "mask", "massacre",
    "master", "mat", "mate", "material", "maternal", "mathematical", "mature",
    "maximum", "meadow", "mechanical", "mechanism", "medal", "median", "medieval",
    "melody", "memorable", "memorial", "memorandum", "merchandise", "merchant",
    "mercy", "merge", "merger", "merit", "mess", "messy", "metaphor", "meter",
    "methodology", "midnight", "midst", "migrate", "militant", "military", "militia",
    "mill", "mingle", "miniature", "minimal", "minimize", "minimum", "mining",
    "minor", "mint", "mirror", "misery", "mislead", "misrepresent", "missile",
    "mistress", "mitigate", "moan", "mob", "mobile", "mobility", "mock", "mode",
    "moderate", "modify", "module", "moist", "moisture", "molecule", "momentum",
    "monetary", "monopoly", "monster", "monthly", "monument", "moral", "mortal",
    "mortgage", "mosaic", "mosque", "mostly", "motherhood", "motion", "motivate",
    "motive", "motor", "motorcycle", "mount", "mourn", "movement", "muddy",
    "multiply", "municipal", "murder", "mushroom", "muscle", "mystery", "myth",
    "nail", "naive", "namely", "narrative", "nasty", "native", "natural", "navigate",
    "navy", "necessity", "necklace", "needle", "negative", "neglect", "negotiate",
    "negotiation", "neighbor", "nephew", "nest", "neutral", "newly", "nice",
    "nickel", "nickname", "niece", "nightmare", "noble", "nod", "nominate", "norm",
    "notable", "notebook", "notion", "novel", "novelist", "nowhere", "nucleus",
    "numerous", "nursery", "nutrition", "oasis", "objection", "objective",
    "obligation", "obscene", "observation", "observer", "obstacle", "obvious",
    "occasion", "occupy", "odds", "offend", "offense", "offensive", "offset",
    "olive", "ongoing", "onset", "opera", "operative", "opponent", "opportunity",
    "opposition", "optical", "optimism", "optimistic", "option", "orbit",
    "orchestra", "organic", "organize", "orientation", "origin", "original",
    "originate", "ornament", "orphan", "outbreak", "outfit", "outlet", "outline",
    "outlook", "output", "outrage", "outrageous", "outset", "outskirt",
    "outstanding", "overcome", "overlook", "overnight", "overseas", "overt",
    "overwhelm", "overwhelming", "ownership", "oxygen", "ozone", "pact", "paddle",
    "palace", "pale", "palm", "pamphlet", "panel", "panic", "parade", "paradise",
    "paradox", "paragraph", "parallel", "paralysis", "parcel", "pardon", "parish",
    "parliament", "parrot", "parsley", "partial", "participant", "participation",
    "particle", "partly", "partner", "passage", "passenger", "passion", "passive",
    "passport", "paste", "patch", "patent", "patience", "patrol", "patron", "pave",
    "pavement", "peak", "peanut", "pearl", "peasant", "pebble", "peculiar",
    "pedestrian", "peek", "peer", "penalty", "pending", "penetrate", "pension",
    "pepper", "perceive", "perception", "perennial", "perfect", "performer",
    "period", "perish", "permanent", "permit", "persist", "persistent",
    "personality", "personnel", "pessimistic", "petition", "petrol", "phase",
    "phenomenon", "philosopher", "philosophy", "phone", "photograph", "photographer",
    "photography", "phrase", "physician", "pianist", "pickup", "pier", "pile",
    "pillar", "pillow", "pilot", "pinch", "pine", "pint", "pioneer", "pistol", "pit",
    "pitch", "plague", "plaid", "plain", "plaintiff", "planet", "planner",
    "plantation", "plasma", "plate", "platform", "platter", "plaza", "plea", "plead",
    "pleading", "pledge", "plum", "plunge", "plural", "plus", "plush", "pocket",
    "poem", "poet", "poetry", "pointed", "polar", "pole", "policy", "polish",
    "polite", "politically", "politician", "poll", "pollute", "pollution", "polygon",
    "pond", "popular", "population", "port", "portal", "portion", "portrait",
    "portray", "pose", "position", "possess", "possession", "possibility",
    "postcard", "poster", "postpone", "potential", "pottery", "poultry", "pound",
    "pour", "poverty", "practical", "practitioner", "praise", "pray", "prayer",
    "preach", "precious", "precise", "precision", "predict", "prediction",
    "predominant", "preferable", "pregnant", "prejudice", "preliminary", "premise",
    "premium", "prescribe", "prescription", "presence", "preservation", "presidency",
    "presidential", "pressure", "prestige", "presumably", "presume", "prevalent",
    "previous", "prey", "priest", "primarily", "primitive", "prince", "principal",
    "principle", "print", "printer", "prior", "priority", "privacy", "privilege",
    "probe", "procedure", "proceed", "process", "proclaim", "procure", "productive",
    "productivity", "profitable", "profound", "progressive", "prohibit", "project",
    "prolong", "prominent", "promote", "prompt", "pronounce", "proof", "propaganda",
    "propel", "proper", "property", "proportion", "proposal", "propose", "prospect",
    "prosperity", "protein", "protest", "protocol", "proud", "prove", "proven",
    "province", "provincial", "provision", "provoke", "prudent", "psychological",
    "psychology", "pub", "publication", "publicity", "pulse", "pump", "punch",
    "punctual", "punish", "purchase", "purple", "purpose", "pursue", "pursuit",
    "puzzle", "pyramid", "qualification", "qualify", "qualitative", "quantitative",
    "quart", "quarter", "quarterly", "query", "quest", "questionnaire", "quota",
    "quote", "rabbit", "racial", "rack", "radar", "radiation", "radical", "radio",
    "rage", "raid", "rail", "railway", "rainbow", "rally", "ranch", "random",
    "range", "rank", "ransom", "rapid", "rare", "rarely", "rash", "rate", "ratio",
    "ration", "rational", "rave", "raw", "ray", "razor", "reach", "react", "readily",
    "reactor", "realistic", "reality", "realize", "realm", "reap", "rear",
    "reasoning", "reassure", "rebel", "rebellion", "rebuke", "recall", "recede",
    "receipt", "recession", "recipe", "recipient", "recite", "reckless", "reckon",
    "reclaim", "recognition", "recognize", "recollect", "recommend", "reconcile",
    "reconstruction", "record", "recount", "recourse", "recover", "recovery",
    "recreation", "recruit", "rectangle", "rectify", "recur", "recyclable",
    "recycle", "redeem", "reduce", "redundant", "referee", "reference", "referendum",
    "reflect", "reform", "refrain", "refresh", "refuge", "refugee", "refund",
    "refuse", "regard", "regardless", "regime", "region", "regional", "register",
    "regret", "regular", "regulate", "regulation", "regulatory", "rehearsal",
    "reign", "reject", "relate", "relative", "relax", "relay", "release", "relevant",
    "reliable", "reliance", "relief", "relieve", "religion", "religious",
    "reluctant", "rely", "remainder", "remark", "remarkable", "remedy", "remind",
    "reminder", "remnant", "remorse", "remote", "removal", "remove", "renaissance",
    "render", "renew", "rent", "rental", "repair", "repay", "repeat", "repeatedly",
    "repel", "repetition", "replace", "replacement", "reply", "report", "repository",
    "represent", "representative", "repression", "reproach", "reproduce", "reptile",
    "republic", "repulse", "reputation", "request", "require", "rescue", "research",
    "resemble", "resent", "reservation", "reserve", "reservoir", "residence",
    "resident", "residential", "resign", "resist", "resistance", "resolve", "resort",
    "resource", "respect", "respective", "respond", "respondent", "response",
    "responsibility", "responsible", "restoration", "restore", "restrain",
    "restraint", "restrict", "restriction", "restructure", "resultant", "result",
    "resume", "retail", "retain", "retire", "retirement", "retreat", "retrieve",
    "return", "reveal", "revenue", "reverse", "review", "revise", "revision",
    "revival", "revive", "revolt", "revolution", "revolutionary", "revolve",
    "reward", "rhetoric", "rhythm", "ribbon", "rice", "rid", "riddle", "ridge",
    "rifle", "rigid", "rigorous", "rim", "riot", "ripe", "ritual", "rival",
    "rivalry", "roam", "robot", "robotics", "robust", "rocket", "rod", "roller",
    "romance", "romantic", "roost", "rotate", "rotation", "rough", "roughly",
    "round", "route", "routine", "royal", "rubber", "rubbish", "ruby", "rugby",
    "ruin", "rule", "ruler", "rumor", "rural", "rust", "sack", "sacred", "sacrifice",
    "saddle", "safeguard", "saint", "salad", "salary", "salmon", "salon",
    "salvation", "sample", "sanction", "sand", "sandwich", "sanity", "satellite",
    "satisfy", "saturate", "sauce", "savage", "scale", "scan", "scandal", "scarce",
    "scare", "scatter", "scenario", "scene", "scent", "scheme", "scholar",
    "scholarship", "schooling", "science", "scientific", "scooter", "scope", "score",
    "scorn", "scout", "scramble", "scrap", "scrape", "scratch", "scream", "screen",
    "screw", "script", "scroll", "scrub", "sculpture", "seal", "seam", "search",
    "season", "seasonal", "seat", "second", "secondary", "section", "sector",
    "secular", "secure", "security", "seed", "seek", "segment", "seize", "select",
    "selection", "seller", "semester", "senate", "senator", "sender", "senior",
    "sensation", "sense", "sensible", "sensitive", "sentence", "sentiment",
    "sequence", "sergeant", "serial", "series", "serious", "servant", "serve",
    "service", "session", "settle", "settlement", "setup", "severe", "shade",
    "shadow", "shaft", "shake", "shallow", "shame", "shape", "shared", "shark",
    "sharp", "shed", "sheer", "sheet", "shelf", "shell", "shelter", "shepherd",
    "shield", "shift", "ship", "shipment", "shipwreck", "shock", "shoot", "shore",
    "short", "shortage", "shortly", "shot", "shove", "shovel", "shower", "shrink",
    "shrug", "shuttle", "sibling", "sickness", "sideways", "siege", "sigh", "sight",
    "sigma", "signal", "signature", "significance", "significant", "silence", "silk",
    "silly", "silver", "similar", "simulate"
) }
