package com.eareyereading.util

/**
 * Collins COBUILD 5星生僻词汇（字母序）。
 *
 * 数据来源：Collins COBUILD Active Study Dictionary 词频数据。
 * 本表为纯数据，由 [CollinsClassifier] 读取并做小写归一化后用于分级查询；
 * 收录 5530 词（源表 5538 条字面量，其中 8 条为重复——
 * Set 语义下去重不改变任何查询结果）。含少量大写条目，查询侧统一小写后命中。
 */
internal val CollinsStar5Words: Set<String> by lazy { setOf(
    "abstraction", "acclaim", "accommodation", "accomplishment", "accountability",
    "accountant", "accreditation", "accumulate", "acknowledgment", "acquisition",
    "acquaintance", "adaptation", "addiction", "adherence", "adjacent", "adjustment",
    "administration", "adolescence", "advancement", "advantageous", "advent",
    "adversary", "adversity", "advertisement", "aesthetic", "affection",
    "affiliation", "affirmative", "affluence", "agenda", "aggravate", "aggregation",
    "agitation", "agnostic", "agony", "algorithm", "alienation", "alignment",
    "allegiance", "allegory", "alliance", "allocation", "alteration", "alternation",
    "alternative", "amalgamation", "ambiguity", "ambiguous", "ameliorate",
    "amendment", "amplification", "analogy", "analytical", "anarchist", "anatomy",
    "ancestor", "ancestry", "anecdote", "animation", "anniversary", "annotation",
    "announcement", "anomalous", "anomaly", "antagonism", "antagonist",
    "anthropology", "antiquity", "anxiously", "apparatus", "appeasement",
    "appellation", "appetizer", "appliance", "applicant", "application",
    "appointment", "appraisal", "appreciation", "apprehension", "arbitration",
    "archaeology", "architectural", "archive", "ardent", "argumentation",
    "aristocracy", "arithmetic", "armor", "aromatic", "arrangement", "articulation",
    "artillery", "artisan", "ascendant", "ascertain", "aspiration", "assassination",
    "assault", "assentation", "asset", "assertion", "assessment", "assignment",
    "assimilation", "assistance", "association", "assurance", "astonishment",
    "astronomy", "asymmetry", "asylum", "atheism", "atmospheric", "attachment",
    "attainment", "attendance", "attorney", "attraction", "attribution", "audacity",
    "audit", "augment", "authentic", "authentication", "authoritative",
    "autobiography", "automation", "autonomous", "availability", "aviation",
    "bankruptcy", "banner", "baptism", "barometer", "barracks", "basement", "batch",
    "batteries", "beacon", "bedroom", "beginning", "behalf", "behaviour",
    "benchmark", "beneficial", "beneficiary", "benevolent", "bilateral", "bilingual",
    "billionaire", "biography", "biological", "biotechnology", "bishop", "bizarre",
    "blade", "blessing", "blockade", "bloom", "blossom", "blueprint", "blunder",
    "boarding", "borough", "bottleneck", "boulder", "boycott", "bracket", "breach",
    "breakdown", "breeding", "brewery", "brigade", "brochure", "brokerage",
    "brotherhood", "browse", "brutality", "buffer", "bulletin", "bureaucracy",
    "burial", "burning", "bushes", "cabinet", "cable", "calculate", "calculation",
    "caliber", "calibration", "calorie", "camaraderie", "campus", "cancellation",
    "candidate", "cane", "canvas", "capacity", "cape", "capitalism", "capitalist",
    "capsule", "caption", "cardboard", "careful", "carpenter", "carriage",
    "cartridge", "cascade", "cashmere", "casting", "casualty", "catalogue",
    "catalyst", "catastrophe", "category", "caterpillar", "cathedral", "caucus",
    "causal", "caution", "cavalry", "ceiling", "celebration", "celebrity", "cellar",
    "census", "centralization", "ceramic", "cereal", "ceremony", "certainty",
    "certification", "cessation", "chain", "chairmanship", "challenge", "chamber",
    "champagne", "champion", "chancellor", "chandelier", "chaos", "characterization",
    "charcoal", "charitable", "charity", "charm", "charter", "chassis", "chateau",
    "chef", "chemical", "cherry", "chicken", "chivalry", "chlorine", "chronic",
    "chronicle", "chronological", "church", "cigarette", "cinema", "circulation",
    "circumference", "circumstance", "civilian", "civilization", "civility",
    "clamor", "clarification", "clarity", "clause", "clearance", "clement", "clergy",
    "clerk", "clientele", "climax", "clockwise", "closet", "closure", "clothing",
    "coalition", "coastal", "coating", "coconut", "cognitive", "coherence",
    "cohesion", "coin", "coincidence", "collaboration", "collateral", "colloquial",
    "colonization", "colon", "colored", "coma", "combatant", "combination",
    "combustion", "comedy", "comet", "commander", "commandment", "commemorate",
    "commencement", "commensurate", "commentary", "commercialization",
    "commissioner", "commodity", "commonplace", "commonwealth", "communal",
    "commune", "communication", "communion", "commutation", "companionship",
    "compatibility", "compensation", "competence", "competitiveness", "compiler",
    "complacency", "completeness", "complexion", "compliance", "complication",
    "compliment", "composition", "compound", "comprehension", "comprehensive",
    "compress", "compromise", "compulsion", "concede", "conceivable",
    "concentration", "conception", "concert", "concession", "conciliation",
    "conclusive", "concordance", "concurrence", "condensation", "condescend",
    "condiment", "condition", "condolence", "conducive", "confer", "confessional",
    "configuration", "confirmation", "conformity", "confrontation", "confusion",
    "congenial", "congestion", "congressional", "conjecture", "conjugation",
    "conjunction", "connection", "connectivity", "connoisseur", "conscientious",
    "consciousness", "consensus", "consequence", "conservation", "conservatism",
    "conservatory", "considerate", "consistency", "consolidation", "consommé",
    "conspiracy", "constable", "constellation", "consternation", "constituency",
    "constitution", "constraint", "construction", "consul", "consultancy",
    "consumption", "contamination", "contemplation", "contempt", "contender",
    "continental", "contingency", "continuation", "continuity", "contour",
    "contraction", "contradiction", "contraption", "contributor", "controversial",
    "convention", "conversation", "conversion", "convertible", "conviction",
    "cooperation", "coordinate", "copper", "copperplate", "copyright", "cordial",
    "corkscrew", "cornerstone", "coronation", "corporation", "correlation",
    "correspondence", "corridor", "corroboration", "corrosion", "corruption",
    "cosmic", "cosmopolitan", "cosmos", "coup", "counterfeit", "countermand",
    "counterpart", "counterpoint", "coupling", "courtyard", "coverage", "covering",
    "cowardice", "coyote", "crackdown", "craftsman", "cramp", "crater", "crawlspace",
    "creation", "credence", "credentials", "credibility", "creed", "creek",
    "cremation", "crescent", "crest", "cricket", "criminality", "crimson",
    "criteria", "critique", "crochet", "crossroads", "crucial", "cruise", "crusade",
    "crystal", "cuisine", "culmination", "cultivation", "curative", "curiosity",
    "curling", "curriculum", "curtailment", "custodian", "customary", "cynicism",
    "dagger", "dartboard", "database", "daughters", "dawn", "deadlock", "dealings",
    "debacle", "debilitating", "decadence", "decathlon", "deceleration",
    "decentralization", "decimation", "declaration", "declassification",
    "declination", "decorum", "decryption", "dedication", "deduction", "defamation",
    "default", "defeatism", "defect", "deference", "defiance", "deficiency",
    "definition", "deflection", "deformation", "degeneration", "degradation",
    "deity", "delay", "delegation", "deliberation", "delinquency", "delirium",
    "deliverance", "demarcation", "dematerialization", "demeanor", "dementia",
    "demilitarization", "demolition", "demonstration", "demoralization",
    "denomination", "denouement", "denunciation", "deodorant", "depression",
    "deputation", "derangement", "derivation", "derivative", "derogatory", "descent",
    "description", "designation", "desperation", "despondent", "destitution",
    "destructible", "desultory", "detachment", "detention", "deterioration",
    "determinant", "determination", "deterrence", "detonation", "detriment",
    "devastation", "development", "deviation", "devotion", "diagnostic", "diagram",
    "dialect", "dialectical", "dialogue", "diameter", "dictatorship", "didactic",
    "diesel", "dietitian", "differentiate", "diffidence", "diffraction", "digestion",
    "digit", "dignitary", "dignity", "dilapidation", "dilation", "dilemma",
    "diligence", "dimension", "diminution", "diplomacy", "directions", "director",
    "directory", "disadvantage", "disaffection", "disagreement", "disappearance",
    "disappointment", "disarm", "disarmament", "disarray", "disaster", "disavowal",
    "disbandment", "disbursement", "discernment", "discharge", "disclaimer",
    "disclosure", "discontinuation", "discordance", "discrepancy", "discretion",
    "discretionary", "discrimination", "discussion", "disdain", "disembark",
    "disenfranchisement", "disengagement", "disentangle", "disfigurement",
    "disgrace", "disguise", "disgust", "dishonesty", "disillusion", "disincentive",
    "disinfection", "disinformation", "disinheritance", "disintegration",
    "dislocation", "disloyalty", "dismantlement", "dismemberment", "disorientation",
    "disparagement", "disparity", "dispassionate", "dispatch", "dispensary",
    "dispensation", "dispersal", "displacement", "disposition", "disproportion",
    "disqualification", "disquisition", "disregarding", "disruption",
    "dissatisfaction", "dissection", "dissemination", "dissidence", "dissolution",
    "dissonance", "distillation", "distinction", "distortion", "distraint",
    "distribution", "disunion", "disunity", "dividend", "divination", "divinity",
    "divisibility", "division", "divulgment", "dockyard", "documentary",
    "documentation", "doctrine", "document", "dogma", "dole", "dolphin",
    "domesticity", "domination", "donation", "donkey", "dormant", "dormitory",
    "dosage", "dove", "downhill", "downstream", "draftsman", "drape", "drastic",
    "drawback", "dredging", "drift", "drill", "drinkable", "dripping", "drought",
    "drumstick", "duality", "dubious", "duchess", "duel", "duke", "dullness",
    "dumping", "dune", "dusk", "duststorm", "dutchess", "duvet", "dwelling",
    "dynamics", "dynasty", "earl", "earnest", "easement", "easter", "eating",
    "eccentric", "eccentricity", "echelon", "eclipse", "ecology", "econometrics",
    "economist", "ecosystem", "ecstasy", "eddy", "edgeways", "edification",
    "edition", "editorial", "educator", "effectiveness", "efficiency", "effluent",
    "ejaculation", "elaboration", "elasticity", "electorate", "electricity",
    "electrochemistry", "electrode", "electrolyte", "electromagnetism", "elegance",
    "elementary", "elevation", "eligibility", "elimination", "elite", "elocution",
    "elongation", "elucidate", "emancipation", "embankment", "embargo",
    "embarkation", "embassy", "embellishment", "embezzlement", "embodiment",
    "embroidery", "emendation", "emergence", "emigration", "eminence", "emission",
    "empathy", "emperor", "emphasis", "emphatic", "empiricism", "emplacement",
    "employability", "empowerment", "emulation", "enactment", "encapsulation",
    "encephalitis", "enchain", "enclosure", "encomium", "encompassment", "encounter",
    "encouragement", "encroachment", "encrustation", "encryption", "endangerment",
    "endearment", "endemic", "endorsement", "endurance", "energizer", "enfeeblement",
    "enforcement", "enfranchisement", "engagement", "engineering", "engulf",
    "enjoyment", "enlightenment", "enlistment", "enmity", "ennui", "enormity",
    "enquiry", "enrichment", "enrollment", "enterprise", "enterprising",
    "entertainment", "enthusiasm", "entitlement", "entity", "entourage", "entrance",
    "entrapment", "entrepreneur", "enumeration", "enunciation", "environment",
    "envoy", "enzyme", "epic", "epidemic", "epidermis", "epigraph", "epilepsy",
    "epilogue", "episode", "epistemology", "equality", "equation", "equestrian",
    "equilibrium", "equipment", "equity", "equivalent", "eradication", "erection",
    "erosion", "errand", "erratic", "erudition", "escalation", "escapade",
    "escarpment", "escheat", "escort", "esoteric", "espionage", "essay", "essence",
    "establishment", "estate", "estimation", "estrange", "ethereal", "ethics",
    "ethnicity", "ethnology", "ethyl", "evaluation", "evaporation", "evasion",
    "event", "eventuality", "evidence", "evolution", "exacerbation", "exactitude",
    "exaggeration", "examination", "exasperation", "excavation", "excellence",
    "exception", "excerpt", "exchange", "exchequer", "excitation", "exclamation",
    "exclusion", "excursion", "execution", "executive", "exegesis", "exemption",
    "exertion", "exfoliation", "exhaustion", "exhibition", "exhortation",
    "exhumation", "exigency", "existence", "exodus", "exoneration", "exorbitant",
    "exorcism", "expansion", "expatriation", "expectation", "expedition",
    "expenditure", "expertise", "expiration", "explanation", "explication",
    "exploitation", "exploration", "exposition", "exposure", "expressway",
    "expropriation", "expulsion", "extermination", "extinction", "extortion",
    "extraction", "extracurricular", "extradition", "extraneous", "extrapolation",
    "fabrics", "fabulous", "facade", "facet", "facilitation", "faction",
    "factitious", "failings", "fairness", "faithfulness", "faker", "fallacy",
    "falsification", "falsity", "familiarity", "famine", "fantasy", "farce",
    "fascination", "fatality", "fatigue", "faucet", "favoritism", "feasibility",
    "feat", "federalism", "feedback", "fellowship", "femininity", "fencing",
    "fender", "fermentation", "ferocious", "ferry", "fertility", "festivity",
    "fetish", "feverish", "fiancé", "fiber", "fictitious", "fidelity", "fiefdom",
    "figment", "filial", "filter", "finale", "finalist", "finality", "financing",
    "finder", "finding", "finery", "fingerling", "fireplace", "firmament", "fishy",
    "fissure", "fistful", "fitness", "fixture", "flair", "flake", "flame", "flap",
    "flaring", "flash", "flask", "flattening", "flattery", "flavoring", "flaw",
    "flax", "flea", "fleet", "flick", "flicker", "flint", "flippancy", "flirtation",
    "flock", "flogging", "flooding", "floppy", "flotation", "flourish",
    "flourishing", "flue", "fluctuation", "fluency", "fluorescent", "flurry",
    "fluster", "flute", "foam", "focal", "focusing", "foggy", "folding", "foliage",
    "folklore", "folly", "foment", "fonder", "font", "foodstuff", "foolhardy",
    "footage", "footbridge", "foothold", "footprint", "footstep", "foray",
    "forbearance", "forbidden", "forceful", "foreboding", "forecast", "forefather",
    "forefront", "foregone", "foreground", "foreknowledge", "forensic", "forestry",
    "forethought", "forewarning", "forfeiture", "forging", "formalism", "formality",
    "formation", "formidable", "formula", "formulation", "forsake", "forte",
    "forthright", "fortification", "fortitude", "forum", "fossil", "fostering",
    "foul", "foundations", "foundry", "fowl", "fraction", "fragment",
    "fragmentation", "fragrance", "framing", "franchise", "frankness", "fraternal",
    "fraternity", "fraudulence", "freakish", "freckle", "freelance", "freethinker",
    "freighter", "frenzied", "frequency", "friction", "frightening", "frigidity",
    "fringe", "frisk", "fritter", "frivolity", "frolic", "frontage", "frontier",
    "frosting", "froth", "frustrating", "fuel", "fugitive", "fulcrum", "fullness",
    "functionality", "funding", "funeral", "funnel", "furor", "furrow",
    "furtherance", "furthermore", "fury", "fuse", "fusion", "fuss", "futile",
    "futility", "gadget", "gage", "gaily", "gait", "galaxy", "gale", "gallery",
    "galley", "gallon", "galvanize", "gambit", "gambling", "gangrene", "gap", "garb",
    "garbage", "gardening", "garment", "garrison", "gash", "gasp", "gateway",
    "gathering", "gauge", "gauntlet", "gauze", "gavel", "gaze", "gearbox", "geek",
    "gel", "geld", "gem", "genealogy", "generality", "generation", "generosity",
    "genesis", "genetics", "geniality", "genocide", "genre", "gentility", "genuine",
    "geography", "geology", "geometry", "geriatric", "gerrymander", "gestation",
    "gesture", "ghetto", "ghostwriter", "giddiness", "gift", "gigantic", "gimmick",
    "glacial", "glacier", "glamour", "glare", "gleaming", "glibness", "glimmer",
    "glimpse", "globalization", "glossary", "glossy", "glove", "glow", "glue",
    "gnome", "goalpost", "goalkeeper", "goatskin", "godsend", "going", "goldsmith",
    "golf", "goner", "gorge", "gospel", "gouge", "governance", "governor",
    "graceful", "gracious", "gradient", "graduation", "graft", "grain", "gram",
    "grammar", "grandeur", "grandmother", "granite", "granny", "granular", "graph",
    "graphics", "grapple", "grasp", "grassland", "grate", "gratification",
    "gratitude", "gratuity", "grave", "gravel", "graveyard", "gravitation", "gray",
    "graze", "grease", "greediness", "greenback", "greeting", "grey", "gridiron",
    "griffin", "grill", "grimace", "grime", "grind", "grip", "grisly", "grit",
    "groan", "groom", "groove", "grope", "grossness", "groundbreaking", "grounding",
    "grouping", "grove", "growl", "grudge", "gruel", "grueling", "grumble", "grunt",
    "guarantee", "guarantor", "guardianship", "guerrilla", "guesthouse", "guidance",
    "guild", "guillotine", "guilt", "guise", "gulch", "gullet", "gullibility",
    "gulp", "gumption", "gunfire", "gunpowder", "gush", "gusto", "gusty", "gutter",
    "gynecology", "haberdashery", "habitability", "hack", "hacker", "haft",
    "haggard", "hail", "haircut", "hairsplitting", "hairy", "halcyon", "halfhearted",
    "halfway", "hallmark", "hallucination", "halo", "halt", "halting", "halve",
    "handbag", "handbook", "handbrake", "handful", "handgun", "handhold",
    "handicraft", "handout", "handrail", "handshake", "handsome", "handwriting",
    "hangar", "hangman", "hangnail", "hankering", "hansom", "haphazard", "harbinger",
    "harbor", "hardback", "hardball", "hardboard", "hardcover", "hardening",
    "hardline", "hardness", "hardship", "hardware", "hardwood", "harebrained",
    "harmful", "harmony", "harness", "harp", "harpoon", "harrow", "harry", "harsh",
    "harvest", "hash", "haste", "hasty", "hatch", "hatchback", "hatchet", "haulage",
    "haunting", "haven", "haversack", "havoc", "hawk", "haystack", "hazard",
    "headboard", "headcount", "headhunter", "headland", "headline", "headmaster",
    "headphone", "headquarters", "headroom", "headset", "headstone", "headway",
    "headwind", "healing", "healthcare", "healthy", "heap", "hearing", "hearsay",
    "hearth", "hearthstone", "heartbeat", "heartbreak", "heartsick", "heartwood",
    "heatstroke", "heave", "heavenly", "heaviness", "hedgehog", "hedgerow",
    "hedonism", "heed", "heel", "heft", "hefty", "hegemony", "heirloom",
    "helicopter", "hellish", "helm", "helmet", "helmsman", "helpless", "hemline",
    "hemoglobin", "hemorrhage", "hemp", "hence", "henceforth", "herald", "herbivore",
    "herd", "hereditary", "heritage", "hermaphrodite", "hermitage", "heroic",
    "heroin", "heroine", "herpes", "hesitation", "heterogeneous", "heterosexual",
    "heuristic", "hexagon", "hibernation", "hideaway", "hidebound", "hideous",
    "hierarchy", "highland", "highlight", "highness", "hijack", "hike", "hiking",
    "hilarious", "hill", "hilly", "hilt", "hindrance", "hindsight", "hippopotamus",
    "hireling", "hiss", "historian", "historical", "hitch", "hitchhike", "hive",
    "hoard", "hoarding", "hoarse", "hobbyhorse", "hockey", "hoist", "holdall",
    "holder", "hole", "holiday", "holler", "hollow", "holly", "holocaust",
    "hologram", "holograph", "homage", "homeland", "homeless", "homemaker",
    "homeowner", "homesick", "homeward", "homework", "homicide", "homogeneous",
    "homosexual", "honeycomb", "honeymoon", "honorary", "hood", "hoodwink", "hoof",
    "hook", "hookup", "hoop", "hope", "hopeful", "horizon", "horizontal", "hormone",
    "horn", "hornet", "horoscope", "horrendous", "horrible", "horrific", "horror",
    "horseback", "horseman", "horseplay", "horsepower", "horseshoe", "horticulture",
    "hospital", "hospitality", "hospitalization", "hostage", "hostel", "hostess",
    "hostility", "hotel", "hound", "hourglass", "houseboat", "housebound",
    "household", "householder", "housekeeper", "housemaid", "houseplant",
    "houseproud", "housewarming", "housing", "hovel", "hovercraft", "howl", "hub",
    "hubbub", "hue", "huff", "hug", "hulk", "hull", "humanism", "humanist",
    "humanitarian", "humankind", "humanoid", "humble", "humid", "humidifier",
    "humidity", "humiliate", "humiliation", "humility", "hummock", "humorist",
    "humorous", "humpback", "humus", "hunchback", "hundredth", "hunger", "hungry",
    "hunk", "hunt", "hunter", "hunting", "hurricane", "hurry", "husbandry", "hush",
    "husk", "husky", "hutch", "hyacinth", "hybrid", "hydra", "hydrocarbon",
    "hydroelectric", "hydrogen", "hydrology", "hydroplane", "hydroponics", "hyena",
    "hygiene", "hygienic", "hymn", "hyperactive", "hyperbola", "hyperlink",
    "hypermarket", "hyperopia", "hypertension", "hypertext", "hyphen",
    "hypnotherapy", "hypnosis", "hypochondria", "hypocrisy", "hypocrite",
    "hypocritical", "hypodermic", "hypoglycemia", "hypotenuse", "hypothermia",
    "hypothesis", "hysteria", "iceberg", "icebound", "icebreaker", "icefall",
    "icicle", "icing", "iconoclast", "idealism", "idealist", "idealize", "ideology",
    "idiocy", "idiom", "idiosyncrasy", "idiot", "idle", "idleness", "idolatry",
    "idolize", "igloo", "ignite", "ignition", "ignominious", "ignominy", "ignorant",
    "ignore", "ill", "illegal", "illegality", "illegible", "illegitimacy", "illicit",
    "illiteracy", "illiterate", "illness", "illogical", "illuminated",
    "illumination", "illusion", "illusory", "illustration", "image", "imagery",
    "imagination", "imaginative", "imaging", "imbalance", "imbroglio", "imbue",
    "imitate", "imitation", "immaculate", "immaterial", "immature", "immeasurable",
    "immemorial", "immense", "immensity", "immerse", "immersion", "immigrant",
    "immigration", "imminence", "imminent", "immobile", "immoderate", "immoral",
    "immortality", "immortalize", "immune", "immunity", "immunization", "impact",
    "impair", "impairment", "impale", "impart", "impartial", "impassable", "impasse",
    "impassioned", "impassive", "impatience", "impeach", "impeachment", "impeccable",
    "impecunious", "impede", "impediment", "impel", "impending", "imperative",
    "imperceptible", "imperfect", "imperial", "imperialism", "imperialist",
    "imperil", "impermanent", "impermissible", "impersonal", "impertinent",
    "impetuous", "impetus", "impiety", "impinge", "impious", "implacable", "implant",
    "implement", "implementation", "implicate", "implication", "implicit", "implore",
    "imply", "impolite", "imponderable", "import", "importance", "important",
    "importation", "importunate", "importune", "impose", "imposing", "imposition",
    "impossibility", "impossible", "impotence", "impotent", "impound", "impoverish",
    "impractical", "imprecation", "impregnable", "impregnate", "impress",
    "impression", "impressionable", "impressive", "imprint", "imprison",
    "imprisonment", "improper", "impropriety", "improve", "improvement",
    "improvisation", "improvise", "imprudent", "impudent", "impulse", "impulsive",
    "impunity", "impure", "impurity", "imputation", "impute", "inability",
    "inaccessibility", "inaccessible", "inaccuracy", "inaccurate", "inaction",
    "inactive", "inactivity", "inadequacy", "inadequate", "inadvertent",
    "inalienable", "inalterable", "inane", "inanimate", "inapplicable",
    "inappropriate", "inapt", "inarticulate", "inasmuch", "inattention",
    "inattentive", "inaudible", "inaugural", "inaugurate", "inauguration", "inborn",
    "inbound", "inbred", "incapable", "incapacitate", "incapacity", "incarcerate",
    "incarceration", "incarnate", "incarnation", "incendiary", "incense",
    "incentive", "inception", "incertitude", "incessant", "incest", "inch",
    "incident", "incidental", "incipient", "incision", "incisive", "incisor",
    "incite", "incitement", "incivility", "incline", "inclination", "include",
    "inclusion", "inclusive", "incogitant", "incognito", "incoherent",
    "incomparable", "incompatible", "incompetence", "incompetent", "incomplete",
    "incomprehensible", "inconceivable", "inconclusive", "incongruous",
    "inconsequent", "inconsequential", "inconsistent", "inconsolable",
    "inconspicuous", "inconstant", "incontestable", "incontrovertible",
    "inconvenience", "inconvenient", "incorporate", "incorrect", "incorrigible",
    "incorruptible", "increase", "incredible", "incredulity", "incredulous",
    "increment", "incriminate", "incrustation", "incubation", "incubator",
    "inculcate", "inculpate", "incumbency", "incumbent", "incur", "incurable",
    "incursion", "indebted", "indecency", "indecent", "indecipherable", "indecision",
    "indecisive", "indeed", "indefatigable", "indefensible", "indefinable",
    "indefinite", "indelible", "indelicate", "indemnify", "indemnity", "indent",
    "indentation", "indenture", "independence", "independent", "indescribable",
    "indestructible", "indeterminate", "indexation", "indicate", "indication",
    "indicative", "indicator", "indict", "indictment", "indifference", "indifferent",
    "indigenous", "indigent", "indigestible", "indigestion", "indignation",
    "indignity", "indirect", "indiscernible", "indiscreet", "indiscretion",
    "indiscriminate", "indispensable", "indisposed", "indisposition", "indisputable",
    "indissoluble", "indistinct", "indistinguishable", "individual", "individualism",
    "individualist", "individuality", "indivisible", "indoctrinate",
    "indoctrination", "indolent", "indomitable", "indoor", "indorse", "indubitable",
    "induce", "inducement", "induct", "induction", "indulge", "indulgence",
    "industrial", "industrialism", "industrialist", "industrialize", "industrious",
    "industry", "ineffective", "ineffectual", "inefficient", "inelegant",
    "ineligible", "ineluctable", "inept", "inequality", "inequitable", "inequity",
    "ineradicable", "inert", "inertia", "inescapable", "inessential", "inestimable",
    "inevitable", "inexact", "inexcusable", "inexhaustible", "inexorable",
    "inexpensive", "inexperience", "inexperienced", "inexpert", "inexplicable",
    "inexpressible", "inextinguishable", "inextricable", "infallibility",
    "infallible", "infamous", "infamy", "infancy", "infant", "infanticide",
    "infantile", "infantry", "infarct", "infection", "infectious", "infelicitous",
    "infer", "inference", "inferior", "inferiority", "infernal", "infertile",
    "infest", "infidel", "infidelity", "infield", "infighting", "infiltrate",
    "infiltration", "infinite", "infinitesimal", "infinity", "infirm", "infirmary",
    "inflame", "inflammation", "inflammatory", "inflatable", "inflate", "inflation",
    "inflationary", "inflection", "inflexibility", "inflexible", "inflict",
    "influence", "influent", "influential", "influenza", "influx", "info",
    "infolding", "informant", "informatics", "information", "informative",
    "informed", "informer", "infraction", "infra-red", "infrastructure",
    "infrequent", "infringe", "infringement", "infuriate", "infuse", "infusion",
    "ingenious", "ingenuity", "ingenuous", "ingestion", "inglorious", "ingrained",
    "ingredient", "ingress", "inhabit", "inhabitant", "inhalant", "inhalation",
    "inhale", "inhaler", "inherent", "inherit", "inheritable", "inheritance",
    "inhibit", "inhibition", "inhospitable", "inhuman", "inhumane", "inimical",
    "inimitable", "iniquitous", "iniquity", "initial", "initialize", "initially",
    "initiate", "initiation", "initiative", "inject", "injection", "injunction",
    "injure", "injurious", "injury", "injustice", "inkblot", "inkle", "inlay",
    "inlet", "inline", "inmate", "innate", "inner", "innermost", "inning",
    "innocence", "innocent", "innocuous", "innovate", "innovation", "innovative",
    "innuendo", "innumerable", "inoculate", "inoculation", "inoffensive",
    "inoperable", "inoperative", "inopportune", "inordinate", "input", "inquest",
    "inquire", "inquiry", "inquisition", "inquisitive", "inquisitor", "insane",
    "insanitary", "insanity", "inscrutable", "insect", "insecticide", "insectivore",
    "insecure", "insecurity", "inseminate", "insemination", "insensible",
    "insensitive", "inseparable", "insert", "insertion", "inset", "inshore",
    "insider", "insidious", "insight", "insightful", "insignificant", "insincere",
    "insinuate", "insinuation", "insipid", "insist", "insistence", "insistent",
    "insolent", "insoluble", "insolvable", "insolvent", "insomnia", "insomniac",
    "inspect", "inspection", "inspector", "inspiration", "inspire", "instability",
    "install", "installation", "installment", "instance", "instant", "instantaneous",
    "instantiate", "instead", "instep", "instigate", "instigation", "instinct",
    "instinctive", "institute", "institution", "institutional", "institutionalize",
    "instruct", "instruction", "instructive", "instructor", "instrument",
    "instrumental", "instrumentality", "instrumentation", "insubordinate",
    "insubordination", "insufferable", "insufficient", "insular", "insulate",
    "insulation", "insulator", "insult", "insulting", "insuperable", "insurable",
    "insurance", "insure", "insured", "insurer", "insurgent", "insurrection",
    "intact", "intake", "intangible", "integer", "integral", "integrate",
    "integration", "integrity", "intellect", "intellectual", "intellectualism",
    "intellectualize", "intelligence", "intelligent", "intelligentsia",
    "intelligible", "intemperance", "intend", "intendant", "intended", "intense",
    "intensifier", "intensify", "intensity", "intensive", "intent", "intention",
    "intentional", "inter", "interact", "interaction", "interactive", "interatomic",
    "interbreed", "intercalary", "intercalate", "intercede", "intercept",
    "interception", "interceptor", "intercession", "interchange", "interchangeable",
    "intercity", "intercollegiate", "intercom", "intercommunicate", "intercommunion",
    "intercontinental", "intercourse", "intercross", "intercurrent", "intercut",
    "interdepend", "interdependence", "interdependency", "interdependent",
    "interest", "interested", "interesting", "interface", "interfacial", "interfere",
    "interference", "interferon", "intergalactic", "intergovernmental", "interim",
    "interior", "interjacent", "interject", "interjection", "interlace", "interlard",
    "interleaf", "interleave", "interlink", "interlock", "interlocutor", "interlope",
    "interloper", "interlude", "intermarriage", "intermeddle", "intermedia",
    "intermediate", "interment", "intermezzo", "interminable", "intermingle",
    "intermission", "intermittent", "intermix", "intermolecular", "internal",
    "internalize", "international", "internecine", "interpenetrate", "interphone",
    "interplanetary", "interplay", "interpolate", "interpolation", "interpose",
    "interposition", "interpret", "interpretation", "interpretative", "interpreter",
    "interpretive", "interracial", "interrelate", "interrelation", "interrogate",
    "interrogation", "interrogative", "interrogator", "interrupt", "interruption",
    "intersect", "intersection", "intersperse", "interstate", "interstellar",
    "interstice", "interstitial", "intertwine", "interurban", "interval",
    "intervene", "intervening", "intervention", "interview", "interweave",
    "intestacy", "intestate", "intestinal", "intestine", "intimacy", "intimate",
    "intimidate", "intimidation", "intolerance", "intolerant", "intonation",
    "intoxicant", "intoxicate", "intracellular", "intramural", "intranet",
    "intransigent", "intransitive", "intrauterine", "intravascular", "intravenous",
    "intrench", "intrepid", "intricacy", "intricate", "intrigue", "intrinsic",
    "introduce", "introduction", "introductory", "introit", "intromit",
    "introspection", "introspective", "introvert", "intrude", "intruder",
    "intrusion", "intrusive", "intuition", "intuitive", "intumescence", "inundate",
    "inundation", "inure", "invade", "invader", "invalid", "invalidate",
    "invalidation", "invalidity", "invaluable", "invariant", "invasion", "invasive",
    "invective", "inveigh", "inveigle", "invent", "invention", "inventive",
    "inventiveness", "inventor", "inventory", "inverse", "inversion", "invert",
    "invertebrate", "invest", "investigate", "investigation", "investigative",
    "investigator", "investigatory", "investment", "investor", "inveterate",
    "invidious", "invigilate", "invigilator", "vigorate", "invigoration",
    "invincible", "inviolable", "inviolate", "invisible", "invitation", "invite",
    "inviting", "invocation", "invoice", "invoke", "involuntary", "involve",
    "involvement", "invulnerability", "invulnerable", "inward", "inwardly",
    "ionosphere", "irate", "ire", "iridescent", "irk", "irksome", "ironclad",
    "ironic", "ironical", "irony", "irradiate", "irrational", "irreclaimable",
    "irreconcilable", "irrecoverable", "irredeemable", "irreducible", "irrefutable",
    "irregular", "irregularity", "irrelevance", "irrelevant", "irreligious",
    "irremediable", "irremovable", "irreparable", "irreplaceable", "irrepressible",
    "irreproachable", "irresistible", "irresolute", "irresolution", "irrespective",
    "irresponsible", "irretrievable", "irreverence", "irreverent", "irreversible",
    "irrevocable", "irrigate", "irrigation", "irritability", "irritable", "irritant",
    "irritate", "irritation", "islet", "isobar", "isolate", "isolation",
    "isolationism", "isomer", "isometric", "isotope", "issue", "isthmus",
    "italicize", "itch", "itchy", "itemize", "iterate", "iteration", "iterative",
    "itinerant", "itinerary", "ivory", "ivy", "jab", "jack", "jackal", "jacket",
    "jackknife", "jade", "jaded", "jail", "jailbird", "jailbreak", "jailer",
    "jalopy", "janitor", "jar", "jasmine", "jaundice", "jaundiced", "jaunt",
    "jaunty", "javelin", "jawbone", "jealous", "jealousy", "jeans", "jeep", "jeer",
    "jejune", "jelly", "jeopardize", "jeopardy", "jerk", "jerkin", "jerky", "jest",
    "jester", "jet", "jettison", "jewel", "jeweler", "jewelry", "jiffy", "jilt",
    "jingle", "jobber", "jobbery", "jobholder", "jock", "jockey", "jocose",
    "jocular", "jocund", "jog", "joggle", "john", "join", "joiner", "jointure",
    "joke", "joker", "joking", "jollification", "jollity", "jolly", "jolt", "jostle",
    "jot", "jounce", "journal", "journalese", "journalism", "journalist",
    "journalistic", "journey", "journeyman", "joust", "joyful", "joyous", "judder",
    "judge", "judgment", "judicial", "judiciary", "judicious", "judo", "jug",
    "juggernaut", "juggle", "jugular", "juice", "juicy", "jumble", "jumbo", "jump",
    "jumper", "jumpsuit", "jumpy", "junco", "junction", "juncture", "jungle",
    "junior", "juniper", "junk", "junket", "junkie", "juridical", "jurisdiction",
    "jurisprudence", "jurist", "juror", "jury", "just", "justice", "justifiable",
    "justification", "justify", "justness", "juvenile", "juxtapose", "juxtaposition",
    "kaffir", "kale", "kampong", "kangaroo", "kapok", "karate", "karma", "kayak",
    "kazoo", "kebab", "keenness", "keep", "kernel", "kerosene", "keyhole",
    "keystone", "keyword", "khaki", "khan", "kibbutz", "kick", "kickback", "kickoff",
    "kidnap", "kidnapper", "kidney", "kill", "killer", "kiln", "kilogram",
    "kilocycle", "kilohertz", "kilometer", "kilowatt", "kilt", "kimono", "kin",
    "kindle", "kindly", "kindness", "kindred", "kinetic", "kingdom", "kink", "kinky",
    "kiosk", "kip", "kipper", "kismet", "kiss", "kit", "kitchen", "kite", "kith",
    "kitten", "kitty", "kiwi", "knack", "knapsack", "knead", "knee", "kneel",
    "knell", "knickers", "knife", "knight", "knighthood", "knit", "knitter",
    "knitting", "knob", "knock", "knocker", "knoll", "knot", "knout", "knowing",
    "knowledge", "knuckle", "koala", "kopeck", "kudos", "kvetch", "kWh", "label",
    "labial", "labor", "laboratory", "laborious", "labour", "labrum", "labyrinth",
    "lace", "lacerate", "laceration", "lack", "lackey", "lackluster", "laconic",
    "lacquer", "lactic", "ladder", "laddie", "ladle", "ladybird", "lag", "lager",
    "laggard", "lagging", "lagoon", "laid", "lair", "lake", "lambaste", "lambent",
    "lament", "lamentable", "lamentation", "laminate", "lamp", "lampoon", "lance",
    "lancet", "landfall", "landfill", "landholder", "landing", "landlady",
    "landless", "landlord", "landlubber", "landmark", "landowner", "landscape",
    "landslide", "lane", "language", "languid", "languish", "languor", "lanky",
    "lap", "lapel", "lapse", "larceny", "lard", "larder", "large", "largesse",
    "lark", "larva", "laryngitis", "larynx", "laser", "lash", "lass", "lasso",
    "last", "lasting", "latch", "late", "lately", "latency", "lateral", "latest",
    "lathe", "lather", "latitude", "latrine", "latter", "lattice", "laugh",
    "laughable", "laughingstock", "laughter", "launch", "launder", "laundress",
    "laundry", "laureate", "laurel", "lavatory", "lavish", "lawful", "lawgiver",
    "lawless", "lawlessness", "lawn", "lawsuit", "lawyer", "laxative", "laxity",
    "layer", "layette", "layman", "layout", "lazaretto", "lazybones", "lea", "leach",
    "lead", "leader", "leadership", "leading", "leaflet", "league", "leakage",
    "leaky", "leaning", "leap", "learned", "learning", "lease", "leasehold", "leash",
    "least", "leather", "leave", "leaven", "leavening", "leaves", "lech", "lecture",
    "lecturer", "ledge", "leech", "leer", "leery", "leeward", "leftist", "leftover",
    "leftward", "legacy", "legal", "legalism", "legality", "legalize", "legate",
    "legatee", "legation", "legend", "legendary", "legerdemain", "legging",
    "legible", "legion", "legislation", "legislative", "legislator", "legislature",
    "legitimacy", "legitimate", "legitimation", "legitimize", "legume", "leguminous",
    "leisure", "leisurely", "lemming", "lemonade", "lend", "length", "lengthen",
    "lengthwise", "lengthy", "lenience", "lenient", "leniency", "lenitive", "lens",
    "lent", "lenticular", "lentil", "leper", "leprosy", "lesbian", "lesion",
    "lessen", "lesser", "lesson", "lest", "letdown", "lethal", "lethargy", "letter",
    "letterbox", "letterhead", "lettering", "lettuce", "leukemia", "level", "lever",
    "leverage", "leviathan", "levitate", "levitation", "levity", "levy", "lexical",
    "lexicographer", "lexicography", "lexicon", "liability", "liable", "liaison",
    "liar", "libation", "libel", "liberal", "liberalism", "liberality", "liberalize",
    "liberate", "liberation", "libertarian", "liberty", "libidinous", "libido",
    "librarian", "library", "libretto", "licence", "license", "licentious", "lichen",
    "lick", "licorice", "lid", "lido", "lie", "lief", "liege", "lien", "lieu",
    "life", "lifeblood", "lifeboat", "lifeguard", "lifeless", "lifeline", "lifelong",
    "lifetime", "lift", "ligament", "ligature", "lighten", "lighter", "lightheaded",
    "lighthearted", "lighthouse", "lightning", "lightsome", "lightyear", "like",
    "likelihood", "likely", "liken", "likeness", "likewise", "lilac", "lilt", "lily",
    "limb", "limber", "limbo", "limeade", "limelight", "limerick", "limestone",
    "limey", "limit", "limitation", "limitless", "limn", "limousine", "limp",
    "limpet", "limpid", "linchpin", "lineage", "lineal", "linear", "lineman",
    "linen", "liner", "lingerie", "linger", "lingo", "linguist", "linguistic",
    "linguistics", "liniment", "lining", "linkage", "linkup", "linnet", "linoleum",
    "linseed", "lint", "lintel", "lion", "lioness", "lipid", "lipoma", "lipstick",
    "liquefaction", "liquefy", "liqueur", "liquid", "liquidate", "liquidation",
    "liquidator", "liquidity", "liquidize", "liquor", "lissom", "list", "listener",
    "listeriosis", "listless", "literal", "literalism", "literalize", "literalness",
    "literary", "literate", "literati", "literature", "lithe", "lithium",
    "lithosphere", "litigant", "litigate", "litigation", "litigious", "litmus",
    "litre", "litter", "litterbug", "little", "littoral", "liturgy", "livable",
    "live", "livelihood", "livelong", "lively", "liver", "liverish", "livery",
    "livid", "living", "lizard", "llama", "loaded", "loader", "loading", "loaf",
    "loafer", "loan", "loanblend", "loath", "loathe", "loathing", "loathsome", "lob",
    "lobby", "lobbyist", "lobe", "lobotomy", "local", "locale", "locality",
    "localize", "locally", "locate", "location", "locative", "lock", "locker",
    "locket", "lockout", "lockup", "locus", "locust", "lodge", "lodger", "lodging",
    "loft", "lofty", "logarithm", "loggerheads", "logic", "logical", "logician",
    "logistics", "logjam", "loincloth", "loiter", "loll", "lollipop", "lonely",
    "loner", "lonesome", "longboat", "longevity", "longhand", "longhorn", "longing",
    "longitude", "longitudinal", "longship", "longshoreman", "look", "lookout",
    "loom", "loon", "loony", "loop", "loophole", "loose", "loosely", "loosen",
    "loot", "looter", "lope", "lopsided", "loquacious", "lord", "lordship", "lore",
    "lorgnette", "lorry", "loser", "lot", "lotion", "lottery", "lotto", "lotus",
    "loud", "loudspeaker", "lough", "lounge", "lounger", "louse", "lousy", "lout",
    "lovable", "love", "lovebird", "loveless", "lovelorn", "lover", "lovesick",
    "lovely", "lower", "lowly", "loyal", "loyalist", "loyalty", "lozenge", "luau",
    "lubber", "lubricant", "lubricate", "lucid", "lucidity", "luck", "luckless",
    "lucky", "lucre", "ludicrous", "lug", "luggage", "lull", "lullaby", "lumbago",
    "lumbar", "lumber", "lumberjack", "luminous", "lump", "lumpen", "lumpy", "lunar",
    "lunatic", "lunch", "luncheon", "lunchtime", "lung", "lunge", "lurch", "lure",
    "lurid", "lurk", "lush", "lust", "lustful", "lustily", "lustrous", "lusty",
    "lute", "luxuriance", "luxuriant", "luxuriate", "luxurious", "luxury", "lying",
    "lymph", "lymphatic", "lymphoma", "lynch", "lynx", "lyre", "lyric", "lyrical",
    "lyricism", "lyricist", "macabre", "macaroni", "macaroon", "machete",
    "machination", "machine", "machinery", "machinist", "macro", "macrobiotic",
    "macrocosm", "macroeconomics", "macron", "madam", "madame", "madcap", "madden",
    "maddening", "made", "madman", "madness", "madrasa", "maelstrom", "maestro",
    "mafia", "magazine", "maggot", "magic", "magical", "magician", "magisterial",
    "magistrate", "magnanimity", "magnanimous", "magnet", "magnetic", "magnetism",
    "magnetize", "magnification", "magnificence", "magnificent", "magnifier",
    "magnify", "magnitude", "magnolia", "magnum", "magpie", "maid", "maiden",
    "maidenhead", "maidenhood", "mail", "mailbox", "mailing", "mailman", "maim",
    "main", "mainland", "mainstream", "maintain", "maintenance", "maisonette",
    "majestic", "majesty", "major", "majority", "make", "maker", "makeshift",
    "makeup", "malachite", "maladapted", "maladjusted", "maladjustment",
    "maladministration", "maladroit", "malady", "malaise", "malapropism", "malaria",
    "malarial", "malcontent", "male", "malefactor", "maleficent", "malevolence",
    "malevolent", "malfeasance", "malfunction", "malice", "malicious", "malign",
    "malignancy", "malignant", "malignity", "malinger", "mall", "mallard", "mallow",
    "malnutrition", "malodorous", "malpractice", "malt", "maltreat", "maltreatment",
    "mama", "mamba", "mamma", "mammal", "mammalian", "mammary", "mammon", "mammoth",
    "manacle", "manage", "manageable", "management", "manager", "manageress",
    "managerial", "mandala", "mandate", "mandatory", "mandolin", "mandrake", "mane",
    "maneuver", "mange", "manger", "mangle", "mango", "mangrove", "mania", "maniac",
    "maniacal", "manic", "manicure", "manifest", "manifestation", "manifesto",
    "manifold", "manikin", "manipulate", "manipulation", "manipulative", "mankind",
    "manlike", "manly", "manna", "mannequin", "manner", "mannerism", "mannerly",
    "manners", "mannish", "manoeuvre", "manor", "manpower", "manslaughter", "mantel",
    "mantelpiece", "mantis", "mantle", "mantrap", "manual", "manufacture",
    "manufacturer", "manumit", "manure", "manuscript", "many", "maple", "marathon",
    "maraud", "marauder", "marble", "marbling", "march", "marchioness", "mare",
    "margarine", "margin", "marginal", "marginalia", "marine", "mariner",
    "marionette", "marital", "maritime", "marjoram", "mark", "markdown", "marker",
    "market", "marketing", "marketplace", "marking", "marksman", "markup",
    "marmalade", "marmoreal", "marrow", "marry", "marsh", "marshal", "marshland",
    "marshy", "marsupial", "mart", "martial", "martin", "martinet", "martyr",
    "martyrdom", "marvel", "marvelous", "mascot", "masculine", "masculinity", "mash",
    "mask", "masking", "masochism", "masochist", "mason", "masonry", "masquerade",
    "massacre", "massage", "masseur", "masseuse", "massive", "mast", "mastectomy",
    "master", "masterful", "masterly", "mastermind", "masterpiece", "mastery",
    "masticate", "mastiff", "masturbate", "masturbation", "matador", "match",
    "matchbox", "matching", "matchless", "matchmaker", "matchstick", "mate",
    "material", "materialism", "materialist", "materialize", "maternal", "maternity",
    "mathematical", "mathematician", "mathematics", "matriarch", "matriarchy",
    "matricide", "matriculate", "matrimony", "matrix", "matron", "matter", "mattery",
    "matting", "mattock", "mattress", "mature", "maturate", "maturation", "maturity",
    "maudlin", "maul", "mausoleum", "mauve", "maxim", "maximal", "maximize",
    "maximum", "mayhem", "mayonnaise", "mayor", "maze", "mead", "meadow", "meager",
    "meal", "mealie", "mealtime", "mealy", "mean", "meander", "meaning",
    "meaningful", "meaningless", "meanness", "means", "meant", "meantime",
    "meanwhile", "measles", "measly", "measure", "measurement", "meat", "meaty",
    "mechanic", "mechanical", "mechanics", "mechanism", "mechanize", "medal",
    "medallion", "medallist", "medic", "medicate", "medication", "medicinal",
    "medicine", "medieval", "mediocre", "mediocrity", "meditate", "meditation",
    "medium", "medley", "meek", "meet", "meeting", "meetinghouse", "megabyte",
    "megahertz", "megalith", "megalomaniac", "megaphone", "melancholy", "mellow",
    "melodic", "melodious", "melodrama", "melody", "melon", "melt", "member",
    "membrane", "memento", "memo", "memoir", "memorable", "memoranda", "memorandum",
    "memorial", "memorize", "memory", "menace", "menagerie", "mend", "mendacious",
    "mendacity", "mendicant", "menial", "meningitis", "menopause", "menses",
    "menstrual", "menstruate", "menstruation", "mental", "mentalism", "mentality",
    "menthol", "mention", "mentor", "menu", "MEP", "mercantile", "mercenary",
    "merchandise", "merchant", "merciless", "mercurial", "Mercury", "mercy", "mere",
    "merely", "merge", "merger", "meridian", "meringue", "merit", "meritocracy",
    "meritocrat", "meritocratic", "mermaid", "merry", "merry-go-round", "mesh",
    "mesmerism", "mesmerize", "mess", "message", "messenger", "Messiah", "messy",
    "metabolism", "metal", "metallic", "metallurgical", "metallurgist", "metallurgy",
    "metalwork", "metamorphosis", "metaphor", "metaphorical", "metaphysics",
    "metastasis", "meteor", "meteoric", "meteorology", "meter", "methadone",
    "methane", "method", "methodical", "methodology", "methyl", "meticulous",
    "metro", "metropolitan", "mettle", "mettlesome", "mew", "mewl", "mews", "mica",
    "microbe", "microbiology", "microchip", "microclimate", "microcomputer",
    "microcosm", "microeconomics", "microelectronics", "microfilm", "micrometer",
    "microphone", "microprocessor", "microscope", "microscopic", "microscopy",
    "microsecond", "microsurgery", "microwave", "midair", "midday", "middle",
    "middleman", "middling", "midge", "midland", "midmost", "midnight", "midpoint",
    "midriff", "midshipman", "midships", "midst", "midsummer", "midterm", "midway",
    "midweek", "midwife", "midwifery", "midwinter", "midyear", "might", "mightily",
    "mighty", "mignon", "migraine", "migrant", "migrate", "migration", "migratory",
    "milch", "mild", "mildew", "mile", "mileage", "milestone", "milieu", "militant",
    "militarism", "militarist", "militarize", "military", "militate", "militia",
    "milk", "milkmaid", "milkman", "milksop", "milkweed", "milky", "mill", "millage",
    "millenarian", "millennial", "millennium", "miller", "millet", "milliner",
    "millinery", "million", "millionaire", "millipede", "millisecond", "millpond",
    "millrace", "millstone", "millwright", "mime", "mimeograph", "mimic", "mimicry",
    "minaret", "mince", "mind", "mindful", "mindless", "mine", "minefield", "miner",
    "mineral", "mineralogy", "minesweeper", "mingle", "mini", "miniature", "minibus",
    "minim", "minimal", "minimalism", "minimalist", "minimize", "minimum", "minion",
    "minister", "ministerial", "ministrant", "ministration", "ministry", "minivan",
    "mink", "minnow", "minor", "minority", "minstrel", "mint", "minuet", "minus",
    "minuscule", "minute", "miracle", "miraculous", "mirage", "mire", "mirror",
    "mirth", "mirthful", "misanthrope", "misanthropy", "misapply", "misapprehend",
    "misapprehension", "misappropriate", "misappropriation", "misbehave",
    "misbehavior", "miscalculate", "miscalculation", "miscall", "miscarriage",
    "miscarry", "miscast", "miscegenation", "miscellan", "miscellany", "mischief",
    "mischief-maker", "mischievous", "misconceive", "misconception", "misconduct",
    "misconstruction", "misconstrue", "miscopy", "miscount", "miscreant", "misdate",
    "misdeal", "misdeed", "misdemeanor", "misdemeanour", "misdirect", "misdirection",
    "misdo", "misdoing", "misemploy", "misemployment", "miser", "miserable",
    "miserly", "misery", "misfire", "misfit", "misfortune", "misgive", "misgiving",
    "misgovern", "misgovernment", "misguide", "misguided", "mishandle", "mishap",
    "mishmash", "misidentify", "misinform", "misinformation", "misinterpret",
    "misinterpretation", "misjudge", "misjudgment", "misknow", "mislabel", "mislead",
    "misleading", "mislearn", "mislike", "mismanage", "mismanagement", "mismatch",
    "misname", "misnomer", "misogamist", "misogamy", "misogynist", "misogyny",
    "misplace", "misprint", "misprize", "mispronounce", "mispronunciation",
    "misquote", "misread", "misreport", "misrepresent", "misrepresentation",
    "misrule", "missal", "misshapen", "missile", "missing", "mission", "missionary",
    "missive", "misspeak", "misspell", "misspelling", "misspend", "misspent",
    "misstate", "misstatement", "misstep", "mist", "mistakable", "mistake", "mister",
    "mistime", "mistral", "mistranslate", "mistranslation", "mistreat",
    "mistreatment", "mistress", "mistrust", "mistrustful", "misty", "misunderstand",
    "misunderstanding", "misunderstood", "misuse", "mite", "mitigate", "mitigation",
    "mitosis", "mitt", "mitten", "mix", "mixer", "mixture", "mix-up", "mnemonic",
    "moan", "moat", "mob", "mobile", "mobilization", "mobilize", "mobster",
    "moccasin", "mock", "mockery", "modal", "mode", "model", "modeling", "modem",
    "moderate", "moderation", "moderator", "modern", "modernism", "modernist",
    "modernity", "modernize", "modest", "modesty", "modicum", "modification",
    "modifier", "modify", "modish", "modular", "modulate", "modulation", "module",
    "modulus", "mogul", "moist", "moisten", "moisture", "molar", "molasses", "mold",
    "moldy", "mole", "molecular", "molecule", "molest", "molestation", "mollify",
    "mollusk", "molt", "molten", "mom", "moment", "momentarily", "momentary",
    "momentous", "momentum", "monger", "mongol", "mongoose", "mongrel", "monitor",
    "monk", "monkey", "monkish", "mono", "monochrome", "monocle", "monocotyledon",
    "monogamy", "monogram", "monograph", "monolith", "monolithic", "monologue",
    "monomania", "monomer", "monomial", "mononucleosis", "monophthong", "monoplane",
    "monopolist", "monopolistic", "monopolize", "monopoly", "monorail",
    "monosyllable", "monotheism", "monotone", "monotonous", "monotony", "monster",
    "monstrance", "monstrosity", "montage", "month", "monthly", "monument",
    "monumental", "moo", "mood", "moody", "moon", "moonbeam", "moonlight", "moonlit",
    "moor", "moorhen", "mooring", "moose", "moot", "mop", "mope", "moped", "mopper",
    "moral", "morale", "moralist", "moralistic", "morality", "moralize", "morally",
    "morass", "moratorium", "morbid", "morbidity", "mordant", "more", "moreover",
    "mores", "moribund", "morn", "morning", "moron", "moronic", "morose", "morph",
    "morpheme", "morphology", "morsel", "mortal", "mortality", "mortar", "mortgage",
    "mortgagee", "mortgagor", "mortician", "mortification", "mortify", "mortise",
    "mortuary", "mosaic", "mosey", "moss", "mossy", "most", "mostly", "motel",
    "motet", "moth", "mothball", "mother", "motherhood", "motherly", "motif",
    "motion", "motionless", "motivate", "motivation", "motive", "motley", "motor",
    "motorbike", "motorboat", "motorbus", "motorcar", "motorcycle", "motorist",
    "motorway", "mottle", "motto", "mould", "mouldy", "moult", "mound", "mount",
    "mountain", "mountaineer", "mountaineering", "mountainous", "mounting", "mourn",
    "mourner", "mournful", "mourning", "mouse", "mousetrap", "mousy", "mouth",
    "mouthful", "mouthpiece", "movable", "move", "movement", "movie", "moviegoer",
    "moving", "mow", "mower", "much", "muck", "mucky", "mucous", "mucus", "mud",
    "muddle", "muddy", "muff", "muffle", "muffler", "mug", "mugger", "muggins",
    "muggy", "mulberry", "mule", "muleteer", "mull", "mullah", "mulse", "multi",
    "multicolored", "multicultural", "multifarious", "multifocal", "multiform",
    "multilateral", "multilingual", "multimedia", "multimillion", "multinational",
    "multiple", "multiplex", "multiplicand", "multiplication", "multiplicity",
    "multiply", "multipolar", "multipurpose", "multiracial", "multistorey",
    "multitude", "multitudinous", "mumble", "mummify", "mummy", "mumps", "munch",
    "municipal", "municipality", "munificent", "mural", "murder", "murderer",
    "murderess", "murderous", "murk", "murky", "murmur", "muscle", "muscular",
    "muse", "museum", "mush", "mushroom", "mushy", "music", "musical", "musician",
    "musicology", "musk", "musket", "musketeer", "musketry", "musky", "muslin",
    "muss", "mussy", "must", "mustache", "mustard", "muster", "musty", "mutable",
    "mutate", "mutation", "mute", "mutilate", "mutilation", "mutineer", "mutinous",
    "mutiny", "mutt", "mutter", "mutton", "mutual", "muzzle", "myopia", "myopic",
    "myriad", "myrrh", "myrtle", "myself", "mysterious", "mystery", "mystic",
    "mystical", "mysticism", "mystification", "mystify", "myth", "mythic",
    "mythical", "mythology", "nacho", "nadir", "nail", "nailbrush", "nailfile",
    "naive", "naivety", "naked", "name", "namedrop", "nameless", "namely",
    "namesake", "nanny", "nap", "napkin", "napoleon", "nappy", "narcolepsy",
    "narcotic", "narrate", "narration", "narrative", "narrator", "narrow",
    "narrow-minded", "nasal", "nascent", "nasturtium", "nasty", "natal", "nation",
    "national", "nationalism", "nationalist", "nationality", "nationalize",
    "nationwide", "native", "nativity", "natter", "natty", "natural", "naturalism",
    "naturalist", "naturalize", "naturally", "nature", "naturist", "naturopathy",
    "naught", "naughty", "nausea", "nauseate", "nauseous", "nautical", "nautilus",
    "naval", "nave", "navel", "navigate", "navigation", "navigator", "navy", "near",
    "nearby", "nearly", "nearside", "nearsighted", "neat", "nebula", "nebulous",
    "necessary", "necessitate", "necessity", "neck", "neckerchief", "necklace",
    "neckline", "necktie", "necrology", "necromancy", "necropolis", "nectar",
    "nectary", "need", "needful", "needle", "needless", "needlessly", "needlework",
    "needy", "negate", "negation", "negative", "negativism", "negativity", "neglect",
    "neglectful", "negligee", "negligence", "negligent", "negligible", "negotiable",
    "negotiant", "negotiate", "negotiation", "negotiator", "neighbor",
    "neighborhood", "neighboring", "neighborly", "neither", "nemesis", "neoclassic",
    "neoclassicism", "neocolonialism", "neon", "neophyte", "neoplasm", "neoplastic",
    "neoplatonism", "nephritis", "nepotism", "nerve", "nerveless", "nervous",
    "nervy", "nest", "nestle", "nestling", "net", "netball", "nether", "nethermost",
    "netherworld", "netting", "nettle", "network", "neural", "neuralgia",
    "neurasthenia", "neurasthenic", "neuroglia", "neurological", "neurologist",
    "neurology", "neuron", "neurosis", "neurotic", "neuroticism", "neuter",
    "neutral", "neutralism", "neutralist", "neutrality", "neutralize", "neutron",
    "never", "nevermore", "nevertheless", "newborn", "newcomer", "newel",
    "newfangled", "newly", "newlywed", "news", "newsagent", "newsboy", "newscast",
    "newscaster", "newsletter", "newspaper", "newsprint", "newsreader", "newsreel",
    "newsstand", "newsy", "newt", "next", "nexus", "nibble", "niccolite", "nice",
    "nicely", "nicety", "niche", "nick", "nickel", "nickname", "nicotine", "niece",
    "niggard", "niggardly", "nigger", "niggle", "niggling", "nigh", "night",
    "nightcap", "nightclothes", "nightclub", "nightfall", "nighthawk", "nightie",
    "nightingale", "nightly", "nightmare", "nightmarish", "nightshade", "nightstick",
    "nighttime", "nightwear", "nihilism", "nihilist", "nimble", "ninepin", "ninety",
    "ninth", "nip", "nipper", "nipping", "nipple", "nippy", "nitrate", "nitric",
    "nitrogen", "nitroglycerin", "nitwit", "nix", "nobility", "noble", "nobly",
    "nobody", "nocturnal", "nocturne", "nod", "nodal", "node", "nodular", "nodule",
    "noise", "noiseless", "noisily", "noisy", "nomad", "nomadic", "nomenclature",
    "nominal", "nominate", "nomination", "nominative", "nominee", "nonage",
    "nonagenarian", "nonce", "nonchalance", "nonchalant", "noncombatant",
    "noncommissioned", "noncommittal", "nonconductor", "nonconformist",
    "nonconformity", "noncontributory", "nondeductible", "non delivery",
    "nondiscriminatory", "none", "nonentity", "nonessential", "nonesuch",
    "nonetheless", "nonfactual", "nonfiction", "nonflammable", "nonintervention",
    "nonpareil", "nonpayment", "nonplus", "nonproliferation", "nonresident",
    "nonrestrictive", "nonrigid", "nonsense", "nonsensical", "nonspecific",
    "nonstandard", "nonstop", "nonsuch", "nonsuit", "nonunion", "nonviolent",
    "nonwhite", "noodle", "nook", "noon", "noonday", "noontide", "noose", "nope",
    "norm", "normal", "normalcy", "normality", "normalization", "normalize",
    "normally", "normative", "north", "northerly", "northern", "northerner",
    "northward", "nose", "nosebag", "nosebleed", "nosegay", "nosey", "notch", "note",
    "notebook", "noted", "noteworthy", "nothing", "notice", "noticeable",
    "notification", "notify", "notion", "notoriety", "notorious", "notwithstanding",
    "nougat", "noun", "nourish", "nourishment", "novel", "novelette", "novelist",
    "novella", "novelty", "novice", "now", "nowadays", "nowhere", "noxious",
    "nozzle", "nuance", "nub", "nubile", "nuclear", "nucleate", "nucleolus",
    "nucleus", "nude", "nudge", "nudist", "nudity", "nugatory", "nugget", "nuisance",
    "null", "nullification", "nullify", "nullity", "numb", "number", "numberless",
    "numbskull", "numeral", "numerate", "numeration", "numeric", "numerical",
    "numerology", "numerous", "numismatic", "numskull", "nun", "nuncio", "nunnery",
    "nurse", "nursemaid", "nursery", "nursling", "nurture", "nut", "nutcracker",
    "nuthatch", "nutmeat", "nutmeg", "nutria", "nutrient", "nutriment", "nutrition",
    "nutritional", "nutritious", "nutritive", "nuts", "nutshell", "nuzzle", "nylon",
    "nymph", "nymphet", "nymphomania", "oaf", "oaken", "oakum", "oar", "oarlock",
    "oarsman", "oasis", "oat", "oath", "obdurate", "obedience", "obedient",
    "obeisance", "obese", "obesity", "obey", "obfuscate", "obfuscation", "obituary",
    "object", "objectify", "objection", "objectionable", "objective", "objectivity",
    "objector", "oblate", "obligate", "obligation", "obligatory", "oblige",
    "obliging", "oblique", "obliterate", "oblivion", "oblivious", "oblong",
    "obloquy", "obnoxious", "oboe", "oboist", "obscene", "obscenity", "obscure",
    "obscurantism", "obscurantist", "obscurity", "obsequies", "obsequious",
    "observance", "observant", "observation", "observatory", "observe", "observer",
    "obsess", "obsessed", "obsession", "obsessive", "obsolescent", "obsolete",
    "obstacle", "obstetric", "obstetrician", "obstinacy", "obstinate",
    "obstreperous", "obstruct", "obstruction", "obstructionist", "obstructive",
    "obtain", "obtainable", "obtrude", "obtrusive", "obtuse", "obverse", "obviate",
    "obvious", "obviously", "ocarina", "occasion", "occasional", "occidental",
    "occiput", "occlude", "occlusion", "occult", "occultism", "occupancy",
    "occupant", "occupation", "occupational", "occupy", "occur", "occurrence",
    "ocean", "oceanic", "ocelot", "ochre", "octagonal", "octave", "octavo",
    "October", "octogenarian", "octopus", "ocular", "odd", "oddity", "oddly", "odds",
    "ode", "odious", "odometer", "odor", "odorous", "offal", "offbeat", "offence",
    "offend", "offender", "offense", "offensive", "offer", "offertory", "offhand",
    "office", "officeholder", "officer", "official", "officially", "officialdom",
    "officiate", "officious", "offing", "offline", "offload", "offprint", "offset",
    "offshoot", "offshore", "offside", "offspring", "offstage", "offtrack", "ogre",
    "oil", "oilcan", "oilcloth", "oiler", "oilfield", "oiliness", "oilskin", "oily",
    "oink", "ointment", "okapi", "okay", "okra", "old", "olden", "oldie",
    "oleaginous", "oleander", "oleograph", "olfactory", "olive", "omega", "omelet",
    "omen", "ominous", "omission", "omit", "omniscient", "omnivorous", "onager",
    "once", "oncoming", "ondograph", "one", "oneirocritic", "oneness", "onerous",
    "oneself", "onetime", "ongoing", "onion", "onlooker", "only", "onset",
    "onslaught", "onto", "ontogeny", "ontology", "onus", "onward", "onyx", "oodles",
    "ooze", "oozy", "opacity", "opal", "opalescent", "opaque", "open", "opener",
    "openly", "openness", "opera", "operable", "operand", "operate", "operatic",
    "operating", "operation", "operational", "operative", "operator", "operetta",
    "ophthalmic", "ophthalmology", "opiate", "opinion", "opinionated", "opium",
    "opossum", "opponent", "opportune", "opportunism", "opportunist", "opportunity",
    "opposable", "oppose", "opposite", "opposition", "oppress", "oppression",
    "oppressive", "oppressor", "opprobrious", "opprobrium", "opt", "optic",
    "optical", "optician", "optics", "optimism", "optimist", "optimistic", "optimum",
    "option", "optional", "optometrist", "optometry", "opulent", "opus", "oracular",
    "oral", "orange", "orangutan", "oration", "orator", "oratorical", "oratorio",
    "oratory", "orb", "orbit", "orbital", "orchard", "orchestra", "orchestral",
    "orchestrate", "orchestration", "orchid", "ordain", "ordeal", "order", "orderly",
    "ordinal", "ordinance", "ordinary", "ordinate", "ordination", "organ", "organic",
    "organism", "organist", "organization", "organize", "organizer", "orient",
    "oriental", "orientate", "orientation", "orifice", "origin", "original",
    "originality", "originally", "originate", "originative", "orison", "ornament",
    "ornamental", "ornamentation", "ornate", "ornery", "orphan", "orphanage",
    "orphaned", "orthodontist", "orthodoxy", "orthogonal", "orthography",
    "oscillate", "oscillation", "oscillator", "osculate", "osier", "osmotic",
    "ossify", "osteitis", "ostensible", "ostentatious", "osteoarthritis",
    "osteopath", "osteopathy", "osteoporosis", "ostracism", "ostracize", "other",
    "otherwise", "otiose", "otter", "ottoman", "ought", "ounce", "our", "ours",
    "ourselves", "oust", "ouster", "out", "outage", "outback", "outbid", "outboard",
    "outbreak", "outbuilding", "outburst", "outcast", "outclass", "outcome",
    "outcrop", "outcry", "outdated", "outdistance", "outdo", "outdoor", "outdoors",
    "outer", "outermost", "outfit", "outfitter", "outflank", "outflow", "outfox",
    "outgrow", "outgrowth", "outhouse", "outing", "outlandish", "outlaw", "outlay",
    "outlet", "outline", "outlive", "output", "outrage", "outrageous", "outreach",
    "outride", "outrigger", "outright", "outrun", "outsell", "outset", "outshine",
    "outside", "outsize", "outskirt", "outsmart", "outsold", "outspoke", "outspoken",
    "outspread", "outstanding", "outstation", "outstretch", "outstrip", "outvote",
    "outward", "outwardly", "outweigh", "outwit", "outwork", "outworn", "ova",
    "oval", "ovary", "ovate", "ovation", "oven", "over", "overact", "overall",
    "overalls", "overarch", "overawe", "overbalance", "overbear", "overbearing",
    "overbid", "overboard", "overburden", "overcast", "overcharge", "overcloud",
    "overcoat", "overcome", "overcompensate", "overconfident", "overcook",
    "overcrowd", "overcurious", "overdo", "overdose", "overdraft", "overdraw",
    "overdress", "overdrive", "overdue", "overeager", "overeat", "overemphasize",
    "overestimate", "overexpose", "overflow", "overfold", "overgarment", "overgrow",
    "overgrown", "overgrowth", "overhand", "overhang", "overhaul", "overhead",
    "overhear", "overheat", "overindulge", "overjoyed", "overkill", "overland",
    "overlap", "overlay", "overleaf", "overlie", "overload", "overlong", "overlook",
    "overlord", "overly", "overmatch", "overmeasure", "overmuch", "overnice",
    "overnight", "overpass", "overpay", "overplay", "overplus", "overpopulated",
    "overpopulation", "overpower", "overprecise", "overpressure", "overprint",
    "overprize", "overproduce", "overproduction", "overprofit", "overprotect",
    "overquick", "overquiet", "overreach", "overreact", "override", "overripe",
    "overrule", "overrun", "overscruppul", "overseas", "oversee", "overseer",
    "oversell", "oversensitive", "oversexed", "overshadow", "overshoe", "overshoot",
    "overshot", "overside", "oversight", "oversimplify", "oversize", "overskirt",
    "oversleep", "overslope", "oversold", "overspend", "overspill", "overstaff",
    "overstate", "overstatement", "overstay", "overstep", "overstock", "overstore",
    "overstrain", "overstress", "overstrict", "overstrung", "overstudy", "overstuff",
    "oversubscribe", "oversubscription", "oversupervise", "overt", "overtake",
    "overtax", "overthink", "overthrew", "overthrow", "overtime", "overtire",
    "overtone", "overtook", "overtop", "overtrain", "overture", "overturn",
    "overuse", "overvaliant", "overvalue", "overview", "overwatch", "overwear",
    "overweary", "overweening", "overweight", "overwhelm", "overwhelming",
    "overwork", "overwrite", "overwrought", "overzealous", "oviduct", "oviparous",
    "ovoid", "ovulate", "ovulation", "ovum", "owe", "owing", "owl", "owlet", "own",
    "owner", "ownership", "oxblood", "oxbow", "oxcart", "oxidation", "oxide",
    "oxidize", "oxygen", "oxymoron", "oyster", "ozone", "pace", "pacemaker",
    "pacific", "pacifism", "pacifist", "pacify", "pack", "package", "packager",
    "packing", "pact", "pad", "padding", "paddle", "paddock", "paddy", "padlock",
    "padre", "paean", "pagan", "paganism", "page", "pageant", "pageantry",
    "pagination", "pager", "pagoda", "paid", "pail", "pailful", "pain", "painful",
    "painless", "pains", "paint", "paintbox", "paintbrush", "painter", "painting",
    "pair", "pajamas", "pal", "palace", "paladin", "palanquin", "palatable",
    "palatal", "palate", "palatial", "palatinate", "palatine", "palaver", "palazzo",
    "pale", "paleface", "paleness", "paleography", "paleontologist", "paleontology",
    "palestra", "palimpsest", "palindrome", "paling", "palisade", "palish", "pall",
    "pallbearer", "pallet", "palliate", "palliation", "palliative", "pallid",
    "pallor", "palm", "palmate", "palmer", "palmistry", "palmtop", "palpable",
    "palpate", "palpitate", "palsy", "palter", "paltry", "pampa", "pamper",
    "pamphlet", "pan", "panacea", "panache", "panama", "pancake", "panchayat",
    "pancreas", "panda", "pandemic", "pander", "pandit", "pane", "panel", "paneling",
    "pang", "panic", "panicky", "panicle", "pannier", "panoply", "panorama", "pant",
    "pantaloon", "pantechnicon", "pantheism", "pantheist", "pantheon", "panther",
    "panties", "pantomime", "pantry", "pants", "panty", "papacy", "papal",
    "papaverine", "papaya", "paper", "paperback", "paperweight", "paperwork",
    "papery", "pappy", "papyrus", "par", "parable", "parabola", "parabolic",
    "paracelsus", "parachute", "parade", "paradigm", "paradigmatic", "paradise",
    "paradox", "paradoxical", "paraffin", "paragon", "paragraph", "parakeet",
    "parallax", "parallel", "parallelled", "parallelism", "parallelogram",
    "paralyse", "paralysis", "paralytic", "paramedic", "parameter", "paramilitary",
    "paramount", "parapet", "paraphernalia", "paraphrase", "paraplegia",
    "paraplegic", "parapsychology", "parasite", "parasitic", "parasol",
    "paratrooper", "paratyphoid", "parboil", "parcel", "parch", "parchment", "pard",
    "pardon", "pardonable", "pardoner", "pare", "parent", "parentage", "parental",
    "parenthesis", "parenthetical", "parget", "parhelion", "pariah", "parietal",
    "paring", "parish", "parishioner", "parity", "park", "parka", "parking",
    "parkland", "parkway", "parlance", "parley", "parliament", "parliamentarian",
    "parlor", "parlour", "parlous", "parmesan", "parochial", "parochialism",
    "parody", "parole", "paronomasia", "paroxysm", "parquet", "parquetry", "parrot",
    "parry", "parse", "parsimonious", "parsimony", "parsley", "parsnip", "parson",
    "parsonage", "part", "partake", "parter", "parterre", "partial", "partiality",
    "partially", "participant", "participate", "participation", "participial",
    "particle", "particolored", "particular", "particularity", "particularize",
    "particularly", "particulate", "parting", "partisan", "partition", "partitive",
    "partly", "partner", "partnership", "partook", "partridge", "parturient",
    "party", "parvenu", "parvis", "parvorder", "parvati", "parvif", "paseo", "pash",
    "pasha", "pass", "passable", "passage", "passageway", "passant", "passbook",
    "passenger", "passer", "passerby", "passim", "passing", "passion", "passionate",
    "passionless", "passive", "passivity", "passkey", "passport", "password", "past",
    "pasta", "paste", "pasteboard", "pastel", "pastern", "pasteurize", "pastiche",
    "pastille", "pastime"
) }
