package com.eareyereading.util

/**
 * Collins COBUILD 1星核心词汇（最常用词，按语义分组排列）。
 *
 * 数据来源：Collins COBUILD Active Study Dictionary 词频数据。
 * 本表为纯数据，由 [CollinsClassifier] 读取并做小写归一化后用于分级查询；
 * 收录 578 词（源表 653 条字面量，其中 75 条为重复——
 * Set 语义下去重不改变任何查询结果）。含少量大写条目，查询侧统一小写后命中。
 */
internal val CollinsStar1Words: Set<String> by lazy { setOf(
    // 冠词/代词/介词
    "a", "an", "the", "i", "you", "he", "she", "it", "we", "they",
    "me", "him", "her", "us", "them", "my", "your", "his", "its",
    "our", "their", "this", "that", "these", "those", "who", "whom",
    "which", "what", "where", "when", "why", "how", "all", "each",
    "every", "both", "few", "more", "most", "other", "some", "such",
    "no", "not", "only", "own", "same", "so", "than", "too", "very",
    "just", "also", "now", "then", "once", "if", "or", "and", "but",
    "in", "on", "at", "by", "for", "with", "about", "against",
    "between", "into", "through", "during", "before", "after",
    "above", "below", "to", "from", "up", "down", "out", "off",
    "over", "under", "again", "further", "here", "there", "any",
    "been", "being", "having", "doing", "made", "make", "get", "got",
    "getting", "go", "going", "went", "gone", "come", "came",
    "coming", "take", "took", "taken", "taking", "see", "saw",
    "seen", "seeing", "know", "knew", "known", "knowing", "think",
    "thought", "thinking", "say", "said", "saying", "tell", "told",
    "ask", "asked", "use", "used", "using", "find",
    "found", "finding", "give", "gave", "given", "giving",
    "seem", "seemed", "may", "might", "must", "would",
    "could", "should", "need", "like", "want", "try", "call",
    "keep", "let", "begin", "help", "show", "hear", "play",
    "run", "move", "live", "believe", "hold", "bring", "happen",
    "write", "provide", "sit", "stand", "lose", "pay", "meet",
    "decide", "return", "explain", "follow", "form", "offer",
    "remember", "love", "consider", "appear", "buy", "wait", "serve",
    "die", "send", "expect", "build", "stay", "fall", "cut", "reach",
    "kill", "remain", "suggest", "raise", "pass", "sell", "require",
    "report", "develop", "agree", "study", "discover", "design",
    "create", "produce", "depend", "accept", "describe", "contain",
    "continue", "increase", "support", "present", "perform",
    "receive", "break", "read", "understand", "improve",
    "determine", "choose", "realize", "achieve", "apply", "argue",
    "identify", "indicate", "exist", "allow", "avoid",
    "finish", "encourage", "involve", "establish", "obtain",
    "generate", "protect", "result", "reduce",
    "control", "cause", "prepare", "affect", "maintain",
    "lead", "seek", "replace", "express", "add", "base", "limit",
    "prove", "represent", "wish", "cover", "include", "afford",
    "face", "fit", "concern", "enjoy", "value", "clear",
    "treat", "gain", "force", "close", "demand", "drive", "drop",
    "feed", "grow", "hang", "hide", "hit", "hurt", "jump",
    "kick", "knock", "lay", "lean", "learn", "leave",
    "lend", "lift", "load", "lock", "look", "matter",
    "mean", "mention", "miss", "notice", "open", "order",
    "pick", "point", "pull", "push", "put",
    "refer", "rest", "rid", "rise", "rub", "save", "search",
    "set", "settle", "shake", "shine", "shoot", "shut", "sign",
    "sing", "slip", "smoke", "snow", "speak", "spend", "spread",
    "stamp", "start", "stick", "stop", "suffer", "supply",
    "suppose", "survive", "switch", "talk", "taste", "throw",
    "touch", "travel", "turn", "visit", "vote", "wake", "walk",
    "warn", "wash", "wear", "weigh", "win", "wonder", "worry",
    "wound", "wrap", "be", "is", "am", "are", "was",
    "were", "have", "has", "had",
    "do", "does", "did", "done", "will", "shall",
    "can", "ought", "dare",
    "word", "time", "year", "people", "way", "day", "man", "woman",
    "child", "children", "world", "life", "hand", "part", "place",
    "case", "week", "company", "system", "program", "question",
    "work", "government", "number", "night", "home",
    "water", "room", "mother", "area", "money", "story", "fact",
    "month", "lot", "right", "book", "eye", "job",
    "business", "issue", "side", "kind", "head", "house", "service",
    "friend", "father", "power", "hour", "game", "line", "end",
    "member", "law", "car", "city", "community", "name", "president",
    "team", "minute", "idea", "kid", "body", "information", "back",
    "parent", "others", "level", "office", "door", "health",
    "person", "art", "war", "history", "party", "change",
    "morning", "reason", "research", "girl", "guy", "moment",
    "air", "teacher", "education", "foot", "feet", "boy",
    "age", "policy", "process", "music", "market", "sense",
    "nation", "plan", "college", "interest", "death", "experience",
    "effect", "class", "care", "field", "development",
    "role", "effort", "rate", "heart", "drug", "leader",
    "light", "voice", "wife", "police", "mind", "difference",
    "period", "student", "picture", "paper", "letter",
    "message", "court", "Laws", "type", "view", "relationship",
    "town", "road", "fire", "bank", "century", "action", "industry",
    "food", "summer", "less",
    "become",
    "thing", "today", "far", "new", "building", "self", "earth",
    "anything", "second", "enough", "almost",
    "everything", "always", "something", "along", "group",
    "among", "however", "yet", "small", "last", "another",
    "big", "high", "actually", "often", "really", "because",
    "around",
    "without", "within", "upon", "across", "toward", "towards",
    "behind", "beyond", "inside", "outside",
    "except", "till", "until", "whether", "while", "although",
    "though", "since", "unless", "neither", "nor", "ever",
    "rather", "quite", "soon", "already", "still", "perhaps",
    "likely", "recently", "finally", "completely", "certainly",
    "especially", "exactly", "immediately", "constantly"
) }
